---
# Code generated by generate.py v1.0.0 from contracts/errors/error-codes.yaml; DO NOT EDIT.
#
# Generator: contracts/tools/generate.py. Edit contracts/errors/error-codes.yaml and run
# `make contracts-generate`. Hand edits are reverted by `make contracts-verify`.
page_title: "Error reference - azureacme provider"
subcategory: ""
description: |-
  Every error code the certificate service can return, with the party who can act on
  it and the next action to take.
---

# Error reference

Every non-2xx response from the certificate service is an RFC 9457
`application/problem+json` document, and every operation failure carries the same
vocabulary in `operation.error.code`. The `code` member is the contract: **branch on
`code` alone**, never on the HTTP status, never on the `title` or `detail` text. A
casing or spelling mismatch is a client bug that no compiler catches and that no fake
service notices, because the fake was built from the same wrong assumption.

Codes are **immutable once published** -- never renamed, never re-spelled, never given
a different meaning, never reused after retirement. A new condition gets a new code,
and a withdrawn code is retired rather than deleted, so a name that ever meant
something never comes back meaning something else.

A code this page does not list is **not** a bug in your client. It is a newer service
talking to an older provider: render the response's own `next_action`, `title`,
`detail` and `request_id`, and treat the condition as non-retryable.

Every code has a stable type URI of `https://mantisec.dev/acme/errors/<code>`.

~> This page is generated from `contracts/errors/error-codes.yaml`. A hand edit is
reverted by the contract drift check. Operator remediation procedure for a code is a
runbook, and is deliberately not on this page.

## How to read a row

| Column | What it tells you |
|---|---|
| `Code` | The machine-readable contract. This, and only this, is what a client branches on. |
| `HTTP` | The status the code is rendered with. `--` for a code that only ever appears inside an operation record. |
| `Surface` | `http` for an HTTP response, `op` for an operation record, `both` for either. An `op` row names the field the code lands in. |
| `Retryable` | Authoritative for the retry classifier. When the body does not parse, fall back to the status: retry 408, 429, 500, 502, 503, 504, transport errors, and 409 **when it carries `Retry-After`**. |
| `Actor` | Who can actually act. Anything other than `caller` means the fix is not in your configuration. |
| `Attribute` | The dotted wire path of the offending field, where the condition has one. |
| `Meaning` | The condition, in one line. |
| `Next action` | The imperative next step. Where the actor is not `caller`, it names the party to ask. |

### Who can act

| `actor` | Who that is |
|---|---|
| `caller` | The team writing the HCL. |
| `namespace_owner` | The owner of the namespace. |
| `platform_admin` | A platform administrator of the certificate service. |
| `vault_owner` | The owner of the destination Key Vault. |
| `dns_owner` | The owner of the DNS zone carrying the challenge name. |
| `ca` | The certificate authority. Nothing to do but wait. |
| `client_bug` | A defect in the API client. The Terraform provider maintainers own the fix. |

## Authentication failures

Section 9.3.1 of the service API contract. The caller has no usable token.

| Code | HTTP | Surface | Retryable | Actor | Attribute | Meaning | Next action |
|---|---|---|---|---|---|---|---|
| `token_audience_mismatch` | 401 | `http` | no | `caller` | -- | The token `aud` claim is not this service's audience. | Set the client's configured audience to {expected_audience} and re-authenticate. |
| `token_tenant_mismatch` | 401 | `http` | no | `caller` | -- | The token `tid` claim is not in the allowed tenant set. | Authenticate in tenant {expected_tenant_id} and retry. |
| `unauthenticated` | 401 | `http` | no | `caller` | -- | No usable token was presented. | Check the credential method the provider actually used, then re-authenticate and retry. |

## Authorisation failures

Section 9.3.2 of the service API contract. 403 for anything the caller may not see, including things that do not exist.

| Code | HTTP | Surface | Retryable | Actor | Attribute | Meaning | Next action |
|---|---|---|---|---|---|---|---|
| `authorisation_denied` | 403 | `http` | no | `platform_admin` | -- | Generic authorisation failure with no more specific code. | Ask your platform administrator for the app role and namespace grant this request needs. |
| `deletion_policy_not_permitted` | 403 | `http` | no | `platform_admin` | `spec.deletion_policy` | The namespace does not permit the requested deletion policy. | Ask your platform administrator to permit the {deletion_policy} deletion policy in namespace {namespace}. |
| `destination_not_authorised` | 403 | `http` | no | `platform_admin` | `spec.destination.key_vault_id` | The vault or certificate name is outside the namespace's destination policies. | Ask your platform administrator to add this vault to the {namespace} namespace's destination policies. |
| `domain_not_authorised` | 403 | `http` | no | `platform_admin` | `spec.dns_names` | One or more requested names are outside the namespace's domain authorisations. | Ask your platform administrator to add {registrable_domain} to the {namespace} namespace's domain authorisations. |
| `namespace_not_authorised` | 403 | `http` | no | `platform_admin` | -- | The namespace is not granted to this caller, or does not exist. Never 404 (spec section 6.1). | Ask your platform administrator for a grant on namespace {namespace}. |
| `operation_not_permitted` | 403 | `http` | no | `platform_admin` | -- | The caller's grant on the namespace does not permit this operation. | Ask your platform administrator to add the {operation} operation to this principal's grant on {namespace}. |
| `principal_not_bound` | 403 | `http` | no | `platform_admin` | -- | No enabled, in-date principal binding exists for this object id. | Ask your platform administrator to bind this principal; a recreated managed identity has a new object id. |
| `role_not_granted` | 403 | `http` | no | `platform_admin` | -- | The caller lacks the app role the endpoint requires. | Ask your platform administrator to assign the {required_role} app role to this principal. |
| `validation_binding_not_authorised` | 403 | `http` | no | `platform_admin` | `spec.validation_binding` | The named validation binding is not available to this namespace. | Ask your platform administrator to grant validation binding {validation_binding} to namespace {namespace}. |
| `wildcard_not_authorised` | 403 | `http` | no | `platform_admin` | `spec.dns_names` | A wildcard identifier requires an explicit wildcard authorisation; it is never inferred from a subtree grant. | Ask your platform administrator for an explicit wildcard authorisation on {base}; a subtree grant never implies one. |

## Request validation

Section 9.3.3 of the service API contract. The request is malformed, or names something the schema or policy cannot accept.

| Code | HTTP | Surface | Retryable | Actor | Attribute | Meaning | Next action |
|---|---|---|---|---|---|---|---|
| `acknowledgement_required` | 400 | `http` | no | `caller` | `spec.acknowledge_irreversible_delete` | A delete deletion policy against a purge-protected vault requires an explicit acknowledgement. | Set spec.acknowledge_irreversible_delete to true, or change the deletion policy to retain. |
| `api_version_unsupported` | 400 | `http` | no | `caller` | -- | The client asked for an API version this service does not serve. | Upgrade the provider to a version speaking one of {api_versions_supported}. |
| `client_too_old` | 400 | `http` | no | `caller` | -- | The client version is below the service's minimum_client_version. | Upgrade the provider to at least version {minimum_client_version} and re-apply. |
| `destination_ambiguous` | 400 | `http` | no | `caller` | `spec.destination.destination_id` | More than one destination policy in the namespace matches the supplied vault id. | Set spec.destination.destination_id to one of {candidates} and re-apply. |
| `destination_incompatible_with_consumer` | 400 | `http` | no | `caller` | `spec.consumer_profile` | The destination or key policy cannot serve the declared consumer profile. | Change the key policy or the consumer profile so they agree, then re-apply. |
| `invalid_identifier` | 422 | `http` | no | `caller` | `spec.dns_names` | A DNS name is not a valid IDNA A-label FQDN under the shared normalisation primitive. | Correct the DNS name and re-apply; the normalisation step rejected it for {reason}. |
| `invalid_page_token` | 400 | `http` | no | `client_bug` | -- | The continuation token does not match this query, or has expired. | Restart the listing without a page token; report a repeat to the Terraform provider maintainers. |
| `invalid_principal_id` | 400 | `http` | no | `caller` | -- | GET /v1/exposure was called with no principal, or with a value that is not a well-formed Entra object id. | Supply the principal's Entra object id as the principal query parameter. |
| `invalid_rekey_reason` | 400 | `http` | no | `caller` | -- | actions/rekey was called with no reason, or a reason outside the three permitted values. | Send a reason of suspected_key_compromise, scheduled_rotation or personnel_change. |
| `invalid_spec` | 400 | `http` | no | `caller` | `spec` | One or more spec fields are invalid; the offending fields are listed in errors[]. | Correct the fields listed in errors[] and re-apply. |
| `spec_immutable_field` | 400 | `http` | no | `caller` | `spec` | A read-only or reserved field was set by the client. | Remove the read-only or reserved field {field} from the request body and re-apply. |
| `subject_name_too_long` | 400 | `both` | no | `caller` | `spec.dns_names` | No DNS name in the set is 64 characters or fewer, so no common name can be formed. | Add a DNS name of 64 characters or fewer to the certificate and re-apply. |
| `too_many_identifiers` | 400 | `http` | no | `caller` | `spec.dns_names` | The request names more identifiers than the ACME profile or the namespace permits. | Split the certificate; this profile and namespace permit at most {max_identifiers} names. |
| `unacceptable_media_type` | 406 | `http` | no | `client_bug` | -- | The Accept header did not permit application/json. | Send Accept application/json; report a repeat to the Terraform provider maintainers. |
| `unsupported_feature` | 400 | `http` | no | `platform_admin` | -- | The request uses a feature this service instance does not advertise. | Ask your platform administrator to upgrade the service to at least {minimum_service_version}, which advertises {feature}. |
| `unsupported_key_type` | 400 | `http` | no | `caller` | `spec.key` | The requested key type is not enabled. RSA-HSM, EC-HSM and Managed HSM destinations are rejected unconditionally. | Choose a key policy this service enables; see key_policies in GET /v1/capabilities. |
| `validation_binding_ambiguous` | 400 | `http` | no | `caller` | `spec.validation_binding` | More than one validation binding could serve these names. | Set spec.validation_binding to one of {candidates} and re-apply. |

## Absence

Section 9.3.4 of the service API contract. Only ever within an authorised namespace.

| Code | HTTP | Surface | Retryable | Actor | Attribute | Meaning | Next action |
|---|---|---|---|---|---|---|---|
| `admin_target_not_found` | 404 | `http` | no | `caller` | -- | The platform-admin object the request named — a migration number, an ownership record — does not exist in this service instance. | Check the migration number or destination hash you named against this service instance and retry; nothing was changed. |
| `dns_challenge_value_not_found` | 404 | `http` | no | `caller` | -- | The named challenge TXT value is not present in the named record set, so the authorised purge removed nothing. | Re-read the record set and repeat the purge with the exact value it holds; nothing was removed. |
| `operation_expired` | 410 | `http` | no | `caller` | -- | The operation is past its archive retention window. | Fall back to the registration and compare observed_generation against target_generation. |
| `operation_not_found` | 404 | `http` | no | `caller` | -- | Unknown operation id. | Fall back to the registration and compare observed_generation against target_generation. |
| `registration_deleted` | 410 | `http` | no | `caller` | -- | The registration was decommissioned. The only 410 that may remove a resource from client state. | Remove the resource from state; the registration was decommissioned at {deleted_at}. |
| `registration_not_found` | 404 | `http` | no | `caller` | -- | No such registration within an authorised namespace. The only 404 that may remove a resource from client state. | Remove the resource from state, or create it; it does not exist in namespace {namespace}. |

## Conflict and precondition failures

Section 9.3.5 of the service API contract.

| Code | HTTP | Surface | Retryable | Actor | Attribute | Meaning | Next action |
|---|---|---|---|---|---|---|---|
| `adoption_pending_operation_present` | 409 | `http` | no | `vault_owner` | -- | An inProgress Key Vault certificate operation exists on the name being adopted, so another system is mid-issuance. | Ask the vault owner to let the in-flight certificate operation finish or cancel it, then adopt again; nothing was adopted. |
| `adoption_san_mismatch` | 409 | `http` | no | `caller` | `spec.dns_names` | The live certificate's dNSName SAN set is not exactly the dns_names the adoption request declared. | Set dns_names to the live certificate's exact dNSName SAN set, or reissue instead of adopting; nothing was adopted. |
| `adoption_thumbprint_mismatch` | 409 | `http` | no | `caller` | -- | The live certificate's SHA-256 thumbprint does not equal the thumbprint the adoption request declared. | Re-read the live certificate's SHA-256 thumbprint and send it as expected_thumbprint_sha256; nothing was adopted. |
| `authorisation_revoked` | 409 | `http` | no | `platform_admin` | -- | The registration's authorisation was withdrawn; renewal has stopped and the published certificate is retained. | Ask your platform administrator to restore the withdrawn grant {withdrawn_grant} on namespace {namespace}. |
| `deletion_policy_conflict` | 409 | `http` | no | `caller` | -- | The request tries to widen the server-persisted deletion policy. | Request policy {persisted_policy} or narrower; the persisted policy was set by {set_by}. |
| `destination_access_denied` | 409 | `http` | yes | `vault_owner` | `spec.destination.key_vault_id` | The publishing identity cannot manage certificates in the destination vault. Retryable — role assignments take several minutes to propagate. | Ask the vault owner to grant {required_role} to principal {principal_id} at {scope}; allow several minutes for propagation. |
| `destination_has_competing_issuer` | 409 | `http` | no | `vault_owner` | -- | The Key Vault certificate policy names a partner issuer or carries an AutoRenew lifetime action. | Ask the vault owner to remove the partner issuer and any AutoRenew lifetime action, then retry. |
| `destination_not_managed` | 409 | `http` | no | `caller` | `spec.destination.certificate_name` | The certificate name exists in the vault but is not managed by this service. | Call POST actions/adopt-certificate to bring the existing certificate under management, or choose another name. |
| `destination_owned_by_another_service_instance` | 409 | `http` | no | `platform_admin` | `spec.destination` | The ownership record names a different service instance. | Ask your platform administrator to resolve the cross-instance claim on this destination before retrying. |
| `destination_owned_elsewhere` | 409 | `http` | no | `caller` | `spec.destination` | Another registration holds the ownership claim for this vault and certificate name. | Choose a different certificate_name, or manage the destination from {owner_namespace}/{owner_name}. |
| `destination_pending_operation_conflict` | 409 | `http` | no (see note) | `platform_admin` | -- | A pending Key Vault certificate operation exists that this service does not own. | Ask your platform administrator to clear the foreign pending certificate operation on this vault object. |
| `destination_raced_by_another_writer` | 409 | `http` | yes | `caller` | -- | A concurrent writer changed the destination mid-operation. | Retry the request; a concurrent writer changed the destination mid-operation. |
| `destination_recently_published` | 409 | `http` | no | `caller` | -- | A delete was refused because the current certificate was published after the caller last observed the registration. | Run terraform refresh (or terraform untaint), confirm the certificate published at {published_at}, then retry. |
| `destination_retained_by_tombstone` | 409 | `http` | no | `caller` | `spec.destination` | A retained-hold claim from a prior retain decommission exists on this destination. | Use POST actions/adopt-certificate to take over the retained certificate, or choose a different certificate_name. |
| `destination_shared` | 409 | `http` | no | `caller` | -- | This registration does not exclusively own the destination, so a destructive deletion is refused. | Delete with policy retain; this registration does not exclusively own the destination. |
| `destination_soft_deleted` | 409 | `http` | no | `vault_owner` | `spec.destination.certificate_name` | The Key Vault certificate object name is in the soft-deleted state. | Call POST actions/recover-destination, or ask the vault owner to purge the soft-deleted object. |
| `destination_unreachable` | 409 | `http` | no | `vault_owner` | `spec.destination.key_vault_id` | The destination vault is not reachable from the service — firewall or private endpoint. | Ask the vault owner to permit the service's outbound address range on the vault firewall. |
| `dns_challenge_value_attribution_mismatch` | 409 | `http` | no | `caller` | -- | The live attribution on the challenge value does not name the service instance the purge request named, so nothing was removed. | Re-read the live attribution and repeat the purge naming {observed_service_instance_id}; nothing was removed. |
| `dns_challenge_value_instance_live` | 409 | `http` | no | `platform_admin` | -- | The challenge value is attributed to a service instance that cannot be treated as decommissioned, so it is never removed automatically and not on request either. | Ask your platform administrator to decommission service instance {service_instance_id}; the value is purgeable no earlier than {purgeable_at}. |
| `dns_record_set_contention` | 409 | `both` | yes | `ca` | -- | Concurrent writers to one TXT record set; retried automatically. | Wait; the service retries automatically and the certificate authority re-checks the challenge. |
| `dns_record_set_full` | 409 | `both` | no | `dns_owner` | -- | The challenge TXT record set is at its capacity ceiling. | Ask the DNS zone owner to remove stale values from TXT record set {record_set_name}. |
| `identifier_claimed_by_another_namespace` | 409 | `http` | no | `platform_admin` | `spec.dns_names` | The DNS-name uniqueness index already holds a claim on this identifier for a different namespace. | Ask your platform administrator to transfer the claim on {identifier}, or remove that name from this certificate. |
| `operation_in_flight` | 409 | `http` | yes | `caller` | -- | A non-terminal operation for the registration's current spec hash exists. | Wait for operation {operation_id} to reach a terminal state, then retry; honour Retry-After. |
| `ownership_conflict` | 409 | `http` | no | `caller` | -- | The registration is owned by a different principal. | Use POST actions/claim to take ownership deliberately, or manage the registration from its owning workspace. |
| `ownership_transfer_required` | 409 | `http` | no | `caller` | -- | The request would transfer ownership implicitly; an explicit claim is required. | Call POST actions/claim with acknowledge_transfer true before importing this registration. |
| `precondition_required` | 428 | `http` | no | `client_bug` | -- | A PUT was sent with neither If-None-Match nor If-Match. | Report to the Terraform provider maintainers; a PUT must carry If-None-Match asterisk or If-Match. |
| `registration_exists` | 409 | `http` | no | `caller` | -- | A different registration already occupies namespace/name, or the spec hash differs from the existing one. | Import the existing registration with terraform import, then re-apply. |
| `spec_revision_conflict` | 412 | `http` | no | `caller` | -- | The registration changed since the plan was made; the If-Match precondition failed. | Run terraform refresh and re-plan; never retry with If-Match asterisk. |
| `validation_binding_unhealthy` | 409 | `http` | yes | `dns_owner` | `spec.validation_binding` | The validation binding's preflight probe is failing. | Ask the DNS zone owner to create CNAME {required_cname} pointing at {required_target}, then retry. |

**Note on `destination_pending_operation_conflict`.** Retryable only when the pending Key Vault certificate operation belongs to this service and is still live; the taxonomy records the conservative value and the runtime may set retryable true with a Retry-After in that one case.

## Rate limiting, quotas and admission control

Section 9.3.6 of the service API contract.

| Code | HTTP | Surface | Retryable | Actor | Attribute | Meaning | Next action |
|---|---|---|---|---|---|---|---|
| `acme_rate_limited` | 429 | `both` | no (see note) | `caller` | -- | A certificate authority rate limit applies. May appear as operation.deferral_reason with an estimated_start days away. | Wait until {reset_at}; do not retry aggressively, because failed attempts consume the same budget. |
| `namespace_quota_exceeded` | 429 | `http` | no | `platform_admin` | -- | A namespace registration or issuance quota is exhausted. | Ask your platform administrator to raise the {limit_name} limit on namespace {namespace}. |
| `publication_rate_guard` | 429 | `both` | no | `caller` | -- | More than five published versions for this registration in 24 hours; an issuance loop is suspected. | Stop re-applying and inspect the registration; more than {threshold} versions were published in 24 hours. |
| `rate_limited` | 429 | `http` | yes | `caller` | -- | The service throttled the request. | Honour Retry-After and retry after {retry_after_seconds} seconds. |
| `validation_budget_exhausted` | 429 | `both` | yes | `caller` | -- | The failed-validation budget for this hostname is exhausted. | Fix the DNS delegation for {hostname} before retrying; failed validations consume the budget. |

**Note on `acme_rate_limited`.** The operation is retried by the scheduler; the HTTP request must not be retried by the client transport. See ADR 0024.

## DNS and validation failures

Section 9.3.7 of the service API contract.

| Code | HTTP | Surface | Retryable | Actor | Attribute | Meaning | Next action |
|---|---|---|---|---|---|---|---|
| `caa_lookup_failed` | 502 | `both` | yes | `ca` | -- | The CAA lookup failed transiently. | Wait and retry; the certificate authority could not complete the CAA lookup. |
| `caa_prohibited` | 400 | `both` | no | `dns_owner` | `spec.dns_names` | A CAA record forbids issuance by this certificate authority. | Ask the DNS zone owner to permit {ca_domain} in the CAA record set on {caa_name}. |
| `dns_cname_loop` | 400 | `both` | no | `dns_owner` | -- | The challenge CNAME chain loops or exceeds its depth limit. | Ask the DNS zone owner to break the CNAME loop at {challenge_name}. |
| `dns_delegation_mismatch` | 400 | `both` | no | `dns_owner` | -- | The _acme-challenge name does not delegate where the binding expects. | Ask the DNS zone owner to create {required_record_type} {challenge_name} pointing at {required_target}. |
| `dns_propagation_timeout` | 504 | `both` | yes | `dns_owner` | -- | The challenge value was not visible on the authoritative nameservers in time. | Ask the DNS zone owner to check the delegation for {challenge_name} and the binding's health, then retry. |
| `dnssec_validation_failure` | 502 | `both` | yes | `dns_owner` | -- | DNSSEC validation of the challenge name failed. | Ask the DNS zone owner to repair the DNSSEC chain of trust for {challenge_name}, then retry. |

## CA and ACME protocol failures

Section 9.3.8 of the service API contract. The ACME engine maps its internal four-class classification onto these codes and introduces none of its own.

| Code | HTTP | Surface | Retryable | Actor | Attribute | Meaning | Next action |
|---|---|---|---|---|---|---|---|
| `acme_authorisation_expired` | -- | `op` in `operation.error.code` | yes | `ca` | -- | A cached authorisation expired mid-order; the order is restarted. | Wait; the certificate authority expired a cached authorisation and the order is restarted automatically. |
| `acme_challenge_failed` | -- | `op` in `operation.error.code` | no | `dns_owner` | -- | A DNS-01 challenge was answered but not accepted by the certificate authority. | Ask the DNS zone owner to confirm {challenge_name} serves only the expected value, then retry. |
| `acme_error` | 502 | `both` | no | `ca` | -- | A sanitised ACME problem document. Carries the ACME problem type and detail, never an order or authorisation URL. | Wait and inspect the sanitised problem type; the certificate authority owns this condition. |
| `acme_order_invalid` | 502 | `both` | no | `caller` | `spec.dns_names` | The CA rejected the order. Per-identifier subproblems are listed in errors[]. | Correct the identifiers named in errors[] and re-apply. |

## Pre-publication verification

Section 9.3.9 of the service API contract. Operation surface only. Nothing is published on any of these.

| Code | HTTP | Surface | Retryable | Actor | Attribute | Meaning | Next action |
|---|---|---|---|---|---|---|---|
| `verify_algorithm_mismatch` | -- | `op` in `operation.error.code` | no, terminal | `platform_admin` | -- | Key type, size or signature algorithm disagrees with the policy. | Ask your platform administrator to investigate; nothing was published and the current certificate is untouched. |
| `verify_chain_untrusted` | -- | `op` in `operation.error.code` | no, terminal | `platform_admin` | -- | The chain does not build to a root in the pinned trust bundle. | Ask your platform administrator to check the pinned trust bundle; a rate of this across registrations must page. |
| `verify_malformed_chain` | -- | `op` in `operation.error.code` | no, terminal | `platform_admin` | -- | The chain does not parse as X.509 v3, or is empty, or is not leaf-first. | Ask your platform administrator to investigate; nothing was published and the current certificate is untouched. |
| `verify_pending_operation_rotated` | -- | `op` in `operation.error.code` | yes | `platform_admin` | -- | The Key Vault pending operation's request id no longer matches the recorded one. | Ask your platform administrator to check for a second writer on this vault object; the service retries with a fresh request. |
| `verify_public_key_mismatch` | -- | `op` in `operation.error.code` | no, terminal | `platform_admin` | -- | The leaf's subject public key does not match the certificate signing request's. | Ask your platform administrator to investigate; nothing was published and the current certificate is untouched. |
| `verify_publish_readback_mismatch` | -- | `op` in `operation.error.code` | yes | `platform_admin` | -- | Post-merge read-back did not return the expected leaf. | Ask your platform administrator to check for a second writer on this vault object; the service retries the read-back. |
| `verify_repeated_failure` | -- | `op` in `operation.error.code` | no, terminal | `platform_admin` | -- | A retryable verification failure has now repeated with a different certificate for the same registration, so the circuit breaker reclassifies it as terminal. | Ask your platform administrator to investigate; further re-issuance is refused because each attempt spends one certificate against the certificate authority's budget. |
| `verify_san_mismatch` | -- | `op` in `operation.error.code` | no, terminal | `platform_admin` | -- | The leaf's dNSName SAN set is not exactly equal to spec.dns_names. | Ask your platform administrator to investigate; a rate of this across registrations means the certificate authority changed something. |
| `verify_stale_specification` | -- | `op` in `operation.error.code` | no, terminal | `platform_admin` | -- | The spec revision recorded with the pending operation is no longer current. | Ask your platform administrator to investigate if this repeats; the operation is superseded and a fresh one runs. |
| `verify_subject_not_in_san` | -- | `op` in `operation.error.code` | no, terminal | `platform_admin` | -- | The leaf's common name is not a member of its SAN set. | Ask your platform administrator to investigate; nothing was published and the current certificate is untouched. |
| `verify_usage_mismatch` | -- | `op` in `operation.error.code` | no, terminal | `platform_admin` | -- | Extended key usage, basic constraints or key usage disagree with the policy. | Ask your platform administrator to investigate; nothing was published and the current certificate is untouched. |
| `verify_validity_window` | -- | `op` in `operation.error.code` | yes | `platform_admin` | -- | not_before or not_after fall outside the accepted window, measured against the storage clock. | Ask your platform administrator to check clock skew between the service and the storage account, then retry. |

`terminal` means the same chain will never pass this check: reissue rather than retry.

## Service and dependency failures

Section 9.3.10 of the service API contract.

| Code | HTTP | Surface | Retryable | Actor | Attribute | Meaning | Next action |
|---|---|---|---|---|---|---|---|
| `catalogue_schema_too_new` | 503 | `http` | no | `platform_admin` | -- | This service build cannot read the catalogue schema version present in storage. | Ask your platform administrator to roll the service forward to a build that reads schema version {catalogue_schema_version}. |
| `dependency_unavailable` | 503 | `http` | yes | `platform_admin` | -- | An upstream dependency (ARM, Key Vault, DNS or the certificate authority) is unavailable. | Retry with backoff; if it persists ask your platform administrator to check the {dependency} dependency. |
| `exposure_inventory_incomplete` | 503 | `http` | yes | `platform_admin` | -- | ARM role-assignment enumeration failed or throttled for one or more destination vaults, so the exposure query would answer partially. | Retry; if it persists ask your platform administrator to grant the service roleAssignments read on {unreadable_scopes}. |
| `internal_error` | 500 | `http` | yes | `platform_admin` | -- | An unexpected internal condition. | Retry with backoff; if it persists give your platform administrator the request id {request_id}. |
| `policy_unavailable` | 503 | `http` | yes | `platform_admin` | -- | The policy store is unreachable. All mutating operations are rejected immediately; reads serve last-known-good for at most 300 seconds. | Retry with backoff; if it persists ask your platform administrator to check the policy store. |
| `restore_pending_acceptance` | 503 | `http` | no | `platform_admin` | -- | The epoch fence is raised after a detected restore; the service is in reconciliation-only mode. | Ask your platform administrator to verify the restore and call POST /v1/admin/accept-restore. |
| `service_unavailable` | 503 | `http` | yes | `platform_admin` | -- | The service is temporarily unable to serve the request. | Retry with backoff; if it persists ask your platform administrator to check service health. |

## Compromise response

Section 9.3.11 of the service API contract. Operation surface only. The second half of a rekey.

| Code | HTTP | Surface | Retryable | Actor | Attribute | Meaning | Next action |
|---|---|---|---|---|---|---|---|
| `rekey_awaiting_consumer_observation` | -- | `op` in `operation.deferral_reason` | no | `caller` | -- | The replacement leaf is published; predecessor revocation is held until the new thumbprint reaches consumer_observed. | Wait for the consumer to pick the new leaf up, or confirm the cut-over window to revoke the predecessor now. |
| `rekey_predecessor_revocation_failed` | -- | `op` in `operation.error.code` | yes | `platform_admin` | -- | The replacement is live but the predecessor was not revoked, so a key believed compromised is still valid. | Ask your platform administrator to retry the revocation and verify the predecessor serial's status with the certificate authority. |

## Withdrawn codes

1 code has been withdrawn from service. A withdrawn code is retired in
`contracts/errors/error-codes.yaml`, never deleted and never reused, and its name
is deliberately not reprinted here: the service will never send it, and a reader
who learns it learns a code that does not exist.
