// Code generated by contracts/tools/generate.py v1.0.0 from contracts/catalogue/*.schema.json; DO NOT EDIT.
//
// Edit contracts/catalogue/*.schema.json and run `make contracts-generate`. Hand edits are reverted by the
// drift check in `make contracts-verify`.

package contracts

// Kind identifies a catalogue document type. Every document carries schemaVersion and
// minReaderVersion; readers fail CLOSED when minReaderVersion exceeds what this build
// supports. A reader that guesses is worse than a reader that stops.
type Kind string

const (
	KindAcmeAccount                   Kind = "AcmeAccount"
	KindBindingHealth                 Kind = "BindingHealth"
	KindCatalogueEpoch                Kind = "CatalogueEpoch"
	KindCertificateRegistrationSpec   Kind = "CertificateRegistrationSpec"
	KindCertificateRegistrationStatus Kind = "CertificateRegistrationStatus"
	KindDestinationOwnership          Kind = "DestinationOwnership"
	KindNameClaim                     Kind = "NameClaim"
	KindOperation                     Kind = "Operation"
	KindServiceInstance               Kind = "ServiceInstance"
	KindTombstone                     Kind = "Tombstone"
)

// AllKinds lists every catalogue document type.
var AllKinds = []Kind{
	KindAcmeAccount,
	KindBindingHealth,
	KindCatalogueEpoch,
	KindCertificateRegistrationSpec,
	KindCertificateRegistrationStatus,
	KindDestinationOwnership,
	KindNameClaim,
	KindOperation,
	KindServiceInstance,
	KindTombstone,
}

// SchemaIDs maps a catalogue kind to the $id of its JSON Schema.
var SchemaIDs = map[Kind]string{
	KindAcmeAccount:                   "https://mantisec.dev/acme/contracts/catalogue/acme-account.schema.json",
	KindBindingHealth:                 "https://mantisec.dev/acme/contracts/catalogue/binding-health.schema.json",
	KindCatalogueEpoch:                "https://mantisec.dev/acme/contracts/catalogue/catalogue-epoch.schema.json",
	KindCertificateRegistrationSpec:   "https://mantisec.dev/acme/contracts/catalogue/certificate-registration-spec.schema.json",
	KindCertificateRegistrationStatus: "https://mantisec.dev/acme/contracts/catalogue/certificate-registration-status.schema.json",
	KindDestinationOwnership:          "https://mantisec.dev/acme/contracts/catalogue/destination-ownership.schema.json",
	KindNameClaim:                     "https://mantisec.dev/acme/contracts/catalogue/name-claim.schema.json",
	KindOperation:                     "https://mantisec.dev/acme/contracts/catalogue/operation.schema.json",
	KindServiceInstance:               "https://mantisec.dev/acme/contracts/catalogue/service-instance.schema.json",
	KindTombstone:                     "https://mantisec.dev/acme/contracts/catalogue/tombstone.schema.json",
}
