// Code generated by contracts/tools/generate.py v1.0.0 from contracts/api/openapi.yaml; DO NOT EDIT.
//
// Edit contracts/api/openapi.yaml and run `make contracts-generate`. Hand edits are reverted by the
// drift check in `make contracts-verify`.

package contracts

// OperationType
//
// A client meeting an UNKNOWN value renders it verbatim and MUST NOT panic or
// map it to a default that changes behaviour.
type OperationType string

const (
	OperationTypeIssue   OperationType = "issue"
	OperationTypeRenew   OperationType = "renew"
	OperationTypeUpdate  OperationType = "update"
	OperationTypeDelete  OperationType = "delete"
	OperationTypeMigrate OperationType = "migrate"
	OperationTypeAdopt   OperationType = "adopt"
	OperationTypeRevoke  OperationType = "revoke"
	OperationTypeRecover OperationType = "recover"
)

// AllOperationTypeValues lists every value known to this build.
var AllOperationTypeValues = []OperationType{
	OperationTypeIssue,
	OperationTypeRenew,
	OperationTypeUpdate,
	OperationTypeDelete,
	OperationTypeMigrate,
	OperationTypeAdopt,
	OperationTypeRevoke,
	OperationTypeRecover,
}

// OperationState -- A client meeting an UNKNOWN state renders it verbatim and MUST NOT panic or
// map it to a default that changes behaviour. `superseded` and `abandoned` are terminal states
// written by the state layer (generation gate and lease steal respectively).
//
// A client meeting an UNKNOWN value renders it verbatim and MUST NOT panic or
// map it to a default that changes behaviour.
type OperationState string

const (
	OperationStatePending    OperationState = "pending"
	OperationStateDeferred   OperationState = "deferred"
	OperationStateRunning    OperationState = "running"
	OperationStateSucceeded  OperationState = "succeeded"
	OperationStateFailed     OperationState = "failed"
	OperationStateCancelled  OperationState = "cancelled"
	OperationStateSuperseded OperationState = "superseded"
	OperationStateAbandoned  OperationState = "abandoned"
)

// AllOperationStateValues lists every value known to this build.
var AllOperationStateValues = []OperationState{
	OperationStatePending,
	OperationStateDeferred,
	OperationStateRunning,
	OperationStateSucceeded,
	OperationStateFailed,
	OperationStateCancelled,
	OperationStateSuperseded,
	OperationStateAbandoned,
}

// RegistrationOperationState -- The state of the registration's CURRENT operation, or `idle`
// when there is none. This is a SUPERSET of the operation record's own `state`: `idle` is the
// absence of an operation and therefore cannot appear on an operation record, which by
// definition exists.
//
// A client meeting an UNKNOWN value renders it verbatim and MUST NOT panic or
// map it to a default that changes behaviour.
type RegistrationOperationState string

const (
	RegistrationOperationStateIdle       RegistrationOperationState = "idle"
	RegistrationOperationStatePending    RegistrationOperationState = "pending"
	RegistrationOperationStateDeferred   RegistrationOperationState = "deferred"
	RegistrationOperationStateRunning    RegistrationOperationState = "running"
	RegistrationOperationStateSucceeded  RegistrationOperationState = "succeeded"
	RegistrationOperationStateFailed     RegistrationOperationState = "failed"
	RegistrationOperationStateCancelled  RegistrationOperationState = "cancelled"
	RegistrationOperationStateSuperseded RegistrationOperationState = "superseded"
	RegistrationOperationStateAbandoned  RegistrationOperationState = "abandoned"
)

// AllRegistrationOperationStateValues lists every value known to this build.
var AllRegistrationOperationStateValues = []RegistrationOperationState{
	RegistrationOperationStateIdle,
	RegistrationOperationStatePending,
	RegistrationOperationStateDeferred,
	RegistrationOperationStateRunning,
	RegistrationOperationStateSucceeded,
	RegistrationOperationStateFailed,
	RegistrationOperationStateCancelled,
	RegistrationOperationStateSuperseded,
	RegistrationOperationStateAbandoned,
}

// OperationPhase -- A STABLE DOCUMENTED ENUM, never free text: it is rendered to the user and
// logged.
//
// A client meeting an UNKNOWN value renders it verbatim and MUST NOT panic or
// map it to a default that changes behaviour.
type OperationPhase string

const (
	OperationPhaseQueued                 OperationPhase = "queued"
	OperationPhasePreparingKey           OperationPhase = "preparing_key"
	OperationPhaseCreatingOrder          OperationPhase = "creating_order"
	OperationPhasePublishingChallenges   OperationPhase = "publishing_challenges"
	OperationPhaseAwaitingDnsPropagation OperationPhase = "awaiting_dns_propagation"
	OperationPhaseAwaitingValidation     OperationPhase = "awaiting_validation"
	OperationPhaseFinalisingOrder        OperationPhase = "finalising_order"
	OperationPhaseVerifyingCertificate   OperationPhase = "verifying_certificate"
	OperationPhasePublishingToKeyVault   OperationPhase = "publishing_to_key_vault"
	OperationPhaseCleaningUp             OperationPhase = "cleaning_up"
	OperationPhaseDone                   OperationPhase = "done"
)

// AllOperationPhaseValues lists every value known to this build.
var AllOperationPhaseValues = []OperationPhase{
	OperationPhaseQueued,
	OperationPhasePreparingKey,
	OperationPhaseCreatingOrder,
	OperationPhasePublishingChallenges,
	OperationPhaseAwaitingDnsPropagation,
	OperationPhaseAwaitingValidation,
	OperationPhaseFinalisingOrder,
	OperationPhaseVerifyingCertificate,
	OperationPhasePublishingToKeyVault,
	OperationPhaseCleaningUp,
	OperationPhaseDone,
}

// DeletionPolicy -- `retain` stops renewal, cancels in-flight work, removes only the challenge
// values this registration owns, moves the destination ownership claim to `retained-hold`
// (never `released`) and writes a tombstone. `delete` adds a soft-delete of the Key Vault
// certificate object, and only when the ownership record shows exclusive ownership.
//
// A client meeting an UNKNOWN value renders it verbatim and MUST NOT panic or
// map it to a default that changes behaviour.
type DeletionPolicy string

const (
	DeletionPolicyRetain DeletionPolicy = "retain"
	DeletionPolicyDelete DeletionPolicy = "delete"
)

// AllDeletionPolicyValues lists every value known to this build.
var AllDeletionPolicyValues = []DeletionPolicy{
	DeletionPolicyRetain,
	DeletionPolicyDelete,
}
