// Code generated by contracts/tools/generate.py v1.0.0 from contracts/errors/error-codes.yaml; DO NOT EDIT.
//
// Edit contracts/errors/error-codes.yaml and run `make contracts-generate`. Hand edits are reverted by the
// drift check in `make contracts-verify`.

package contracts

import "errors"

// Code is the machine-readable error contract. Clients branch on Code ALONE -- never on
// the HTTP status, never on Title or Detail text. A casing or spelling mismatch is a
// client bug no compiler catches, that a fake service built from the same wrong
// assumption does not catch, and that surfaces only against the real service.
//
// Codes are IMMUTABLE once published: never renamed, never re-spelled, never given a
// different meaning, never reused after retirement.
type Code string

const (
	// A delete deletion policy against a purge-protected vault requires an explicit
	// acknowledgement.
	CodeAcknowledgementRequired Code = "acknowledgement_required"
	// A cached authorisation expired mid-order; the order is restarted.
	CodeACMEAuthorisationExpired Code = "acme_authorisation_expired"
	// A DNS-01 challenge was answered but not accepted by the certificate authority.
	CodeACMEChallengeFailed Code = "acme_challenge_failed"
	// A sanitised ACME problem document. Carries the ACME problem type and detail, never an order
	// or authorisation URL.
	CodeACMEError Code = "acme_error"
	// The CA rejected the order. Per-identifier subproblems are listed in errors[].
	CodeACMEOrderInvalid Code = "acme_order_invalid"
	// A certificate authority rate limit applies. May appear as operation.deferral_reason with an
	// estimated_start days away.
	CodeACMERateLimited Code = "acme_rate_limited"
	// The client asked for an API version this service does not serve.
	CodeAPIVersionUnsupported Code = "api_version_unsupported"
	// Generic authorisation failure with no more specific code.
	CodeAuthorisationDenied Code = "authorisation_denied"
	// The registration's authorisation was withdrawn; renewal has stopped and the published
	// certificate is retained.
	CodeAuthorisationRevoked Code = "authorisation_revoked"
	// The CAA lookup failed transiently.
	CodeCAALookupFailed Code = "caa_lookup_failed"
	// A CAA record forbids issuance by this certificate authority.
	CodeCAAProhibited Code = "caa_prohibited"
	// This service build cannot read the catalogue schema version present in storage.
	CodeCatalogueSchemaTooNew Code = "catalogue_schema_too_new"
	// The client version is below the service's minimum_client_version.
	CodeClientTooOld Code = "client_too_old"
	// The request tries to widen the server-persisted deletion policy.
	CodeDeletionPolicyConflict Code = "deletion_policy_conflict"
	// The namespace does not permit the requested deletion policy.
	CodeDeletionPolicyNotPermitted Code = "deletion_policy_not_permitted"
	// An upstream dependency (ARM, Key Vault, DNS or the certificate authority) is unavailable.
	CodeDependencyUnavailable Code = "dependency_unavailable"
	// The publishing identity cannot manage certificates in the destination vault. Retryable —
	// role assignments take several minutes to propagate.
	CodeDestinationAccessDenied Code = "destination_access_denied"
	// More than one destination policy in the namespace matches the supplied vault id.
	CodeDestinationAmbiguous Code = "destination_ambiguous"
	// The Key Vault certificate policy names a partner issuer or carries an AutoRenew lifetime
	// action.
	CodeDestinationHasCompetingIssuer Code = "destination_has_competing_issuer"
	// The destination or key policy cannot serve the declared consumer profile.
	CodeDestinationIncompatibleWithConsumer Code = "destination_incompatible_with_consumer"
	// The vault or certificate name is outside the namespace's destination policies.
	CodeDestinationNotAuthorised Code = "destination_not_authorised"
	// The certificate name exists in the vault but is not managed by this service.
	CodeDestinationNotManaged Code = "destination_not_managed"
	// The ownership record names a different service instance.
	CodeDestinationOwnedByAnotherServiceInstance Code = "destination_owned_by_another_service_instance"
	// Another registration holds the ownership claim for this vault and certificate name.
	CodeDestinationOwnedElsewhere Code = "destination_owned_elsewhere"
	// A pending Key Vault certificate operation exists that this service does not own.
	CodeDestinationPendingOperationConflict Code = "destination_pending_operation_conflict"
	// A concurrent writer changed the destination mid-operation.
	CodeDestinationRacedByAnotherWriter Code = "destination_raced_by_another_writer"
	// A delete was refused because the current certificate was published after the caller last
	// observed the registration.
	CodeDestinationRecentlyPublished Code = "destination_recently_published"
	// A retained-hold claim from a prior retain decommission exists on this destination.
	CodeDestinationRetainedByTombstone Code = "destination_retained_by_tombstone"
	// This registration does not exclusively own the destination, so a destructive deletion is
	// refused.
	CodeDestinationShared Code = "destination_shared"
	// The Key Vault certificate object name is in the soft-deleted state.
	CodeDestinationSoftDeleted Code = "destination_soft_deleted"
	// The destination vault is not reachable from the service — firewall or private endpoint.
	CodeDestinationUnreachable Code = "destination_unreachable"
	// The challenge CNAME chain loops or exceeds its depth limit.
	CodeDNSCnameLoop Code = "dns_cname_loop"
	// The _acme-challenge name does not delegate where the binding expects.
	CodeDNSDelegationMismatch Code = "dns_delegation_mismatch"
	// The challenge value was not visible on the authoritative nameservers in time.
	CodeDNSPropagationTimeout Code = "dns_propagation_timeout"
	// Concurrent writers to one TXT record set; retried automatically.
	CodeDNSRecordSetContention Code = "dns_record_set_contention"
	// The challenge TXT record set is at its capacity ceiling.
	CodeDNSRecordSetFull Code = "dns_record_set_full"
	// DNSSEC validation of the challenge name failed.
	CodeDnssecValidationFailure Code = "dnssec_validation_failure"
	// One or more requested names are outside the namespace's domain authorisations.
	CodeDomainNotAuthorised Code = "domain_not_authorised"
	// ARM role-assignment enumeration failed or throttled for one or more destination vaults, so
	// the exposure query would answer partially.
	CodeExposureInventoryIncomplete Code = "exposure_inventory_incomplete"
	// An unexpected internal condition.
	CodeInternalError Code = "internal_error"
	// A DNS name is not a valid IDNA A-label FQDN under the shared normalisation primitive.
	CodeInvalidIdentifier Code = "invalid_identifier"
	// The continuation token does not match this query, or has expired.
	CodeInvalidPageToken Code = "invalid_page_token"
	// GET /v1/exposure was called with no principal, or with a value that is not a well-formed
	// Entra object id.
	CodeInvalidPrincipalID Code = "invalid_principal_id"
	// actions/rekey was called with no reason, or a reason outside the three permitted values.
	CodeInvalidRekeyReason Code = "invalid_rekey_reason"
	// One or more spec fields are invalid; the offending fields are listed in errors[].
	CodeInvalidSpec Code = "invalid_spec"
	// The namespace is not granted to this caller, or does not exist. Never 404 (spec section
	// 6.1).
	CodeNamespaceNotAuthorised Code = "namespace_not_authorised"
	// A namespace registration or issuance quota is exhausted.
	CodeNamespaceQuotaExceeded Code = "namespace_quota_exceeded"
	// The operation is past its archive retention window.
	CodeOperationExpired Code = "operation_expired"
	// A non-terminal operation for the registration's current spec hash exists.
	CodeOperationInFlight Code = "operation_in_flight"
	// Unknown operation id.
	CodeOperationNotFound Code = "operation_not_found"
	// The caller's grant on the namespace does not permit this operation.
	CodeOperationNotPermitted Code = "operation_not_permitted"
	// The registration is owned by a different principal.
	CodeOwnershipConflict Code = "ownership_conflict"
	// The request would transfer ownership implicitly; an explicit claim is required.
	CodeOwnershipTransferRequired Code = "ownership_transfer_required"
	// The policy store is unreachable. All mutating operations are rejected immediately; reads
	// serve last-known-good for at most 300 seconds.
	CodePolicyUnavailable Code = "policy_unavailable"
	// A PUT was sent with neither If-None-Match nor If-Match.
	CodePreconditionRequired Code = "precondition_required"
	// No enabled, in-date principal binding exists for this object id.
	CodePrincipalNotBound Code = "principal_not_bound"
	// More than five published versions for this registration in 24 hours; an issuance loop is
	// suspected.
	CodePublicationRateGuard Code = "publication_rate_guard"
	// The service throttled the request.
	CodeRateLimited Code = "rate_limited"
	// The registration was decommissioned. The only 410 that may remove a resource from client
	// state.
	CodeRegistrationDeleted Code = "registration_deleted"
	// A different registration already occupies namespace/name, or the spec hash differs from the
	// existing one.
	CodeRegistrationExists Code = "registration_exists"
	// No such registration within an authorised namespace. The only 404 that may remove a resource
	// from client state.
	CodeRegistrationNotFound Code = "registration_not_found"
	// The replacement leaf is published; predecessor revocation is held until the new thumbprint
	// reaches consumer_observed.
	CodeRekeyAwaitingConsumerObservation Code = "rekey_awaiting_consumer_observation"
	// The replacement is live but the predecessor was not revoked, so a key believed compromised
	// is still valid.
	CodeRekeyPredecessorRevocationFailed Code = "rekey_predecessor_revocation_failed"
	// The epoch fence is raised after a detected restore; the service is in reconciliation-only
	// mode.
	CodeRestorePendingAcceptance Code = "restore_pending_acceptance"
	// The caller lacks the app role the endpoint requires.
	CodeRoleNotGranted Code = "role_not_granted"
	// The service is temporarily unable to serve the request.
	CodeServiceUnavailable Code = "service_unavailable"
	// A read-only or reserved field was set by the client.
	CodeSpecImmutableField Code = "spec_immutable_field"
	// The registration changed since the plan was made; the If-Match precondition failed.
	CodeSpecRevisionConflict Code = "spec_revision_conflict"
	// No DNS name in the set is 64 characters or fewer, so no common name can be formed.
	CodeSubjectNameTooLong Code = "subject_name_too_long"
	// The token `aud` claim is not this service's audience.
	CodeTokenAudienceMismatch Code = "token_audience_mismatch"
	// The token `tid` claim is not in the allowed tenant set.
	CodeTokenTenantMismatch Code = "token_tenant_mismatch"
	// The request names more identifiers than the ACME profile or the namespace permits.
	CodeTooManyIdentifiers Code = "too_many_identifiers"
	// The Accept header did not permit application/json.
	CodeUnacceptableMediaType Code = "unacceptable_media_type"
	// No usable token was presented.
	CodeUnauthenticated Code = "unauthenticated"
	// The request uses a feature this service instance does not advertise.
	CodeUnsupportedFeature Code = "unsupported_feature"
	// The requested key type is not enabled. RSA-HSM, EC-HSM and Managed HSM destinations are
	// rejected unconditionally.
	CodeUnsupportedKeyType Code = "unsupported_key_type"
	// More than one validation binding could serve these names.
	CodeValidationBindingAmbiguous Code = "validation_binding_ambiguous"
	// The named validation binding is not available to this namespace.
	CodeValidationBindingNotAuthorised Code = "validation_binding_not_authorised"
	// The validation binding's preflight probe is failing.
	CodeValidationBindingUnhealthy Code = "validation_binding_unhealthy"
	// The failed-validation budget for this hostname is exhausted.
	CodeValidationBudgetExhausted Code = "validation_budget_exhausted"
	// Key type, size or signature algorithm disagrees with the policy.
	CodeVerifyAlgorithmMismatch Code = "verify_algorithm_mismatch"
	// The chain does not build to a root in the pinned trust bundle.
	CodeVerifyChainUntrusted Code = "verify_chain_untrusted"
	// The chain does not parse as X.509 v3, or is empty, or is not leaf-first.
	CodeVerifyMalformedChain Code = "verify_malformed_chain"
	// The Key Vault pending operation's request id no longer matches the recorded one.
	CodeVerifyPendingOperationRotated Code = "verify_pending_operation_rotated"
	// The leaf's subject public key does not match the certificate signing request's.
	CodeVerifyPublicKeyMismatch Code = "verify_public_key_mismatch"
	// Post-merge read-back did not return the expected leaf.
	CodeVerifyPublishReadbackMismatch Code = "verify_publish_readback_mismatch"
	// The leaf's dNSName SAN set is not exactly equal to spec.dns_names.
	CodeVerifySanMismatch Code = "verify_san_mismatch"
	// The spec revision recorded with the pending operation is no longer current.
	CodeVerifyStaleSpecification Code = "verify_stale_specification"
	// The leaf's common name is not a member of its SAN set.
	CodeVerifySubjectNotInSan Code = "verify_subject_not_in_san"
	// Extended key usage, basic constraints or key usage disagree with the policy.
	CodeVerifyUsageMismatch Code = "verify_usage_mismatch"
	// not_before or not_after fall outside the accepted window, measured against the storage
	// clock.
	CodeVerifyValidityWindow Code = "verify_validity_window"
	// A wildcard identifier requires an explicit wildcard authorisation; it is never inferred from
	// a subtree grant.
	CodeWildcardNotAuthorised Code = "wildcard_not_authorised"
)

// Actor names who can act on a condition. A code whose Actor is not ActorCaller carries
// a NextAction that names the party to ask, in the imperative.
type Actor string

const (
	ActorCA            Actor = "ca"
	ActorCaller        Actor = "caller"
	ActorClientBug     Actor = "client_bug"
	ActorDNSOwner      Actor = "dns_owner"
	ActorPlatformAdmin Actor = "platform_admin"
	ActorVaultOwner    Actor = "vault_owner"
)

// Surface says where a code can appear: on an HTTP response, in an operation record, or
// both.
type Surface string

const (
	SurfaceHTTP Surface = "http"
	SurfaceOp   Surface = "op"
	SurfaceBoth Surface = "both"
)

// Metadata is the generated projection of one taxonomy entry.
type Metadata struct {
	Code          Code
	Category      string
	HTTPStatus    int
	Surface       Surface
	Retryable     bool
	Actor         Actor
	AttributePath string
	Title         string
	NextAction    string
	Meaning       string
}

var metadata = map[Code]Metadata{
	CodeAcknowledgementRequired: {
		Code:          CodeAcknowledgementRequired,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec.acknowledge_irreversible_delete",
		Title:         "Irreversible-delete acknowledgement required",
		NextAction:    "Set spec.acknowledge_irreversible_delete to true, or change the deletion policy to retain.",
		Meaning:       "A delete deletion policy against a purge-protected vault requires an explicit acknowledgement.",
	},
	CodeACMEAuthorisationExpired: {
		Code:          CodeACMEAuthorisationExpired,
		Category:      "ca_acme",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     true,
		Actor:         ActorCA,
		AttributePath: "",
		Title:         "Cached authorisation expired",
		NextAction:    "Wait; the certificate authority expired a cached authorisation and the order is restarted automatically.",
		Meaning:       "A cached authorisation expired mid-order; the order is restarted.",
	},
	CodeACMEChallengeFailed: {
		Code:          CodeACMEChallengeFailed,
		Category:      "ca_acme",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     false,
		Actor:         ActorDNSOwner,
		AttributePath: "",
		Title:         "DNS-01 challenge was not accepted",
		NextAction:    "Ask the DNS zone owner to confirm {challenge_name} serves only the expected value, then retry.",
		Meaning:       "A DNS-01 challenge was answered but not accepted by the certificate authority.",
	},
	CodeACMEError: {
		Code:          CodeACMEError,
		Category:      "ca_acme",
		HTTPStatus:    502,
		Surface:       SurfaceBoth,
		Retryable:     false,
		Actor:         ActorCA,
		AttributePath: "",
		Title:         "Certificate authority returned a problem",
		NextAction:    "Wait and inspect the sanitised problem type; the certificate authority owns this condition.",
		Meaning:       "A sanitised ACME problem document. Carries the ACME problem type and detail, never an order or authorisation URL.",
	},
	CodeACMEOrderInvalid: {
		Code:          CodeACMEOrderInvalid,
		Category:      "ca_acme",
		HTTPStatus:    502,
		Surface:       SurfaceBoth,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec.dns_names",
		Title:         "Certificate authority rejected the order",
		NextAction:    "Correct the identifiers named in errors[] and re-apply.",
		Meaning:       "The CA rejected the order. Per-identifier subproblems are listed in errors[].",
	},
	CodeACMERateLimited: {
		Code:          CodeACMERateLimited,
		Category:      "rate_limiting",
		HTTPStatus:    429,
		Surface:       SurfaceBoth,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Certificate authority rate limit reached",
		NextAction:    "Wait until {reset_at}; do not retry aggressively, because failed attempts consume the same budget.",
		Meaning:       "A certificate authority rate limit applies. May appear as operation.deferral_reason with an estimated_start days away.",
	},
	CodeAPIVersionUnsupported: {
		Code:          CodeAPIVersionUnsupported,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "API version not supported",
		NextAction:    "Upgrade the provider to a version speaking one of {api_versions_supported}.",
		Meaning:       "The client asked for an API version this service does not serve.",
	},
	CodeAuthorisationDenied: {
		Code:          CodeAuthorisationDenied,
		Category:      "authorisation",
		HTTPStatus:    403,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Authorisation denied",
		NextAction:    "Ask your platform administrator for the app role and namespace grant this request needs.",
		Meaning:       "Generic authorisation failure with no more specific code.",
	},
	CodeAuthorisationRevoked: {
		Code:          CodeAuthorisationRevoked,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Authorisation revoked",
		NextAction:    "Ask your platform administrator to restore the withdrawn grant {withdrawn_grant} on namespace {namespace}.",
		Meaning:       "The registration's authorisation was withdrawn; renewal has stopped and the published certificate is retained.",
	},
	CodeCAALookupFailed: {
		Code:          CodeCAALookupFailed,
		Category:      "dns_validation",
		HTTPStatus:    502,
		Surface:       SurfaceBoth,
		Retryable:     true,
		Actor:         ActorCA,
		AttributePath: "",
		Title:         "CAA lookup failed",
		NextAction:    "Wait and retry; the certificate authority could not complete the CAA lookup.",
		Meaning:       "The CAA lookup failed transiently.",
	},
	CodeCAAProhibited: {
		Code:          CodeCAAProhibited,
		Category:      "dns_validation",
		HTTPStatus:    400,
		Surface:       SurfaceBoth,
		Retryable:     false,
		Actor:         ActorDNSOwner,
		AttributePath: "spec.dns_names",
		Title:         "CAA record prohibits issuance",
		NextAction:    "Ask the DNS zone owner to permit {ca_domain} in the CAA record set on {caa_name}.",
		Meaning:       "A CAA record forbids issuance by this certificate authority.",
	},
	CodeCatalogueSchemaTooNew: {
		Code:          CodeCatalogueSchemaTooNew,
		Category:      "service_dependency",
		HTTPStatus:    503,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Catalogue schema is newer than this build",
		NextAction:    "Ask your platform administrator to roll the service forward to a build that reads schema version {catalogue_schema_version}.",
		Meaning:       "This service build cannot read the catalogue schema version present in storage.",
	},
	CodeClientTooOld: {
		Code:          CodeClientTooOld,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Client version too old",
		NextAction:    "Upgrade the provider to at least version {minimum_client_version} and re-apply.",
		Meaning:       "The client version is below the service's minimum_client_version.",
	},
	CodeDeletionPolicyConflict: {
		Code:          CodeDeletionPolicyConflict,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Deletion policy conflict",
		NextAction:    "Request policy {persisted_policy} or narrower; the persisted policy was set by {set_by}.",
		Meaning:       "The request tries to widen the server-persisted deletion policy.",
	},
	CodeDeletionPolicyNotPermitted: {
		Code:          CodeDeletionPolicyNotPermitted,
		Category:      "authorisation",
		HTTPStatus:    403,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "spec.deletion_policy",
		Title:         "Deletion policy not permitted",
		NextAction:    "Ask your platform administrator to permit the {deletion_policy} deletion policy in namespace {namespace}.",
		Meaning:       "The namespace does not permit the requested deletion policy.",
	},
	CodeDependencyUnavailable: {
		Code:          CodeDependencyUnavailable,
		Category:      "service_dependency",
		HTTPStatus:    503,
		Surface:       SurfaceHTTP,
		Retryable:     true,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Upstream dependency unavailable",
		NextAction:    "Retry with backoff; if it persists ask your platform administrator to check the {dependency} dependency.",
		Meaning:       "An upstream dependency (ARM, Key Vault, DNS or the certificate authority) is unavailable.",
	},
	CodeDestinationAccessDenied: {
		Code:          CodeDestinationAccessDenied,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     true,
		Actor:         ActorVaultOwner,
		AttributePath: "spec.destination.key_vault_id",
		Title:         "Destination access denied",
		NextAction:    "Ask the vault owner to grant {required_role} to principal {principal_id} at {scope}; allow several minutes for propagation.",
		Meaning:       "The publishing identity cannot manage certificates in the destination vault. Retryable \u2014 role assignments take several minutes to propagate.",
	},
	CodeDestinationAmbiguous: {
		Code:          CodeDestinationAmbiguous,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec.destination.destination_id",
		Title:         "Destination is ambiguous",
		NextAction:    "Set spec.destination.destination_id to one of {candidates} and re-apply.",
		Meaning:       "More than one destination policy in the namespace matches the supplied vault id.",
	},
	CodeDestinationHasCompetingIssuer: {
		Code:          CodeDestinationHasCompetingIssuer,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorVaultOwner,
		AttributePath: "",
		Title:         "Destination has a competing issuer",
		NextAction:    "Ask the vault owner to remove the partner issuer and any AutoRenew lifetime action, then retry.",
		Meaning:       "The Key Vault certificate policy names a partner issuer or carries an AutoRenew lifetime action.",
	},
	CodeDestinationIncompatibleWithConsumer: {
		Code:          CodeDestinationIncompatibleWithConsumer,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec.consumer_profile",
		Title:         "Destination incompatible with the declared consumer",
		NextAction:    "Change the key policy or the consumer profile so they agree, then re-apply.",
		Meaning:       "The destination or key policy cannot serve the declared consumer profile.",
	},
	CodeDestinationNotAuthorised: {
		Code:          CodeDestinationNotAuthorised,
		Category:      "authorisation",
		HTTPStatus:    403,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "spec.destination.key_vault_id",
		Title:         "Destination not authorised",
		NextAction:    "Ask your platform administrator to add this vault to the {namespace} namespace's destination policies.",
		Meaning:       "The vault or certificate name is outside the namespace's destination policies.",
	},
	CodeDestinationNotManaged: {
		Code:          CodeDestinationNotManaged,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec.destination.certificate_name",
		Title:         "Destination certificate not managed by this service",
		NextAction:    "Call POST actions/adopt-certificate to bring the existing certificate under management, or choose another name.",
		Meaning:       "The certificate name exists in the vault but is not managed by this service.",
	},
	CodeDestinationOwnedByAnotherServiceInstance: {
		Code:          CodeDestinationOwnedByAnotherServiceInstance,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "spec.destination",
		Title:         "Destination owned by another service instance",
		NextAction:    "Ask your platform administrator to resolve the cross-instance claim on this destination before retrying.",
		Meaning:       "The ownership record names a different service instance.",
	},
	CodeDestinationOwnedElsewhere: {
		Code:          CodeDestinationOwnedElsewhere,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec.destination",
		Title:         "Destination owned by another registration",
		NextAction:    "Choose a different certificate_name, or manage the destination from {owner_namespace}/{owner_name}.",
		Meaning:       "Another registration holds the ownership claim for this vault and certificate name.",
	},
	CodeDestinationPendingOperationConflict: {
		Code:          CodeDestinationPendingOperationConflict,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Pending certificate operation conflict",
		NextAction:    "Ask your platform administrator to clear the foreign pending certificate operation on this vault object.",
		Meaning:       "A pending Key Vault certificate operation exists that this service does not own.",
	},
	CodeDestinationRacedByAnotherWriter: {
		Code:          CodeDestinationRacedByAnotherWriter,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     true,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Destination raced by another writer",
		NextAction:    "Retry the request; a concurrent writer changed the destination mid-operation.",
		Meaning:       "A concurrent writer changed the destination mid-operation.",
	},
	CodeDestinationRecentlyPublished: {
		Code:          CodeDestinationRecentlyPublished,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Refusing to delete a recently published certificate",
		NextAction:    "Run terraform refresh (or terraform untaint), confirm the certificate published at {published_at}, then retry.",
		Meaning:       "A delete was refused because the current certificate was published after the caller last observed the registration.",
	},
	CodeDestinationRetainedByTombstone: {
		Code:          CodeDestinationRetainedByTombstone,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec.destination",
		Title:         "Destination retained by a tombstone",
		NextAction:    "Use POST actions/adopt-certificate to take over the retained certificate, or choose a different certificate_name.",
		Meaning:       "A retained-hold claim from a prior retain decommission exists on this destination.",
	},
	CodeDestinationShared: {
		Code:          CodeDestinationShared,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Destination is shared",
		NextAction:    "Delete with policy retain; this registration does not exclusively own the destination.",
		Meaning:       "This registration does not exclusively own the destination, so a destructive deletion is refused.",
	},
	CodeDestinationSoftDeleted: {
		Code:          CodeDestinationSoftDeleted,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorVaultOwner,
		AttributePath: "spec.destination.certificate_name",
		Title:         "Destination certificate is soft-deleted",
		NextAction:    "Call POST actions/recover-destination, or ask the vault owner to purge the soft-deleted object.",
		Meaning:       "The Key Vault certificate object name is in the soft-deleted state.",
	},
	CodeDestinationUnreachable: {
		Code:          CodeDestinationUnreachable,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorVaultOwner,
		AttributePath: "spec.destination.key_vault_id",
		Title:         "Destination unreachable",
		NextAction:    "Ask the vault owner to permit the service's outbound address range on the vault firewall.",
		Meaning:       "The destination vault is not reachable from the service \u2014 firewall or private endpoint.",
	},
	CodeDNSCnameLoop: {
		Code:          CodeDNSCnameLoop,
		Category:      "dns_validation",
		HTTPStatus:    400,
		Surface:       SurfaceBoth,
		Retryable:     false,
		Actor:         ActorDNSOwner,
		AttributePath: "",
		Title:         "DNS CNAME chain loops",
		NextAction:    "Ask the DNS zone owner to break the CNAME loop at {challenge_name}.",
		Meaning:       "The challenge CNAME chain loops or exceeds its depth limit.",
	},
	CodeDNSDelegationMismatch: {
		Code:          CodeDNSDelegationMismatch,
		Category:      "dns_validation",
		HTTPStatus:    400,
		Surface:       SurfaceBoth,
		Retryable:     false,
		Actor:         ActorDNSOwner,
		AttributePath: "",
		Title:         "DNS delegation mismatch",
		NextAction:    "Ask the DNS zone owner to create {required_record_type} {challenge_name} pointing at {required_target}.",
		Meaning:       "The _acme-challenge name does not delegate where the binding expects.",
	},
	CodeDNSPropagationTimeout: {
		Code:          CodeDNSPropagationTimeout,
		Category:      "dns_validation",
		HTTPStatus:    504,
		Surface:       SurfaceBoth,
		Retryable:     true,
		Actor:         ActorDNSOwner,
		AttributePath: "",
		Title:         "DNS propagation timed out",
		NextAction:    "Ask the DNS zone owner to check the delegation for {challenge_name} and the binding's health, then retry.",
		Meaning:       "The challenge value was not visible on the authoritative nameservers in time.",
	},
	CodeDNSRecordSetContention: {
		Code:          CodeDNSRecordSetContention,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceBoth,
		Retryable:     true,
		Actor:         ActorCA,
		AttributePath: "",
		Title:         "Challenge record set contention",
		NextAction:    "Wait; the service retries automatically and the certificate authority re-checks the challenge.",
		Meaning:       "Concurrent writers to one TXT record set; retried automatically.",
	},
	CodeDNSRecordSetFull: {
		Code:          CodeDNSRecordSetFull,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceBoth,
		Retryable:     false,
		Actor:         ActorDNSOwner,
		AttributePath: "",
		Title:         "Challenge record set is full",
		NextAction:    "Ask the DNS zone owner to remove stale values from TXT record set {record_set_name}.",
		Meaning:       "The challenge TXT record set is at its capacity ceiling.",
	},
	CodeDnssecValidationFailure: {
		Code:          CodeDnssecValidationFailure,
		Category:      "dns_validation",
		HTTPStatus:    502,
		Surface:       SurfaceBoth,
		Retryable:     true,
		Actor:         ActorDNSOwner,
		AttributePath: "",
		Title:         "DNSSEC validation failed",
		NextAction:    "Ask the DNS zone owner to repair the DNSSEC chain of trust for {challenge_name}, then retry.",
		Meaning:       "DNSSEC validation of the challenge name failed.",
	},
	CodeDomainNotAuthorised: {
		Code:          CodeDomainNotAuthorised,
		Category:      "authorisation",
		HTTPStatus:    403,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "spec.dns_names",
		Title:         "Domain not authorised for this caller",
		NextAction:    "Ask your platform administrator to add {registrable_domain} to the {namespace} namespace's domain authorisations.",
		Meaning:       "One or more requested names are outside the namespace's domain authorisations.",
	},
	CodeExposureInventoryIncomplete: {
		Code:          CodeExposureInventoryIncomplete,
		Category:      "service_dependency",
		HTTPStatus:    503,
		Surface:       SurfaceHTTP,
		Retryable:     true,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Exposure inventory is incomplete",
		NextAction:    "Retry; if it persists ask your platform administrator to grant the service roleAssignments read on {unreadable_scopes}.",
		Meaning:       "ARM role-assignment enumeration failed or throttled for one or more destination vaults, so the exposure query would answer partially.",
	},
	CodeInternalError: {
		Code:          CodeInternalError,
		Category:      "service_dependency",
		HTTPStatus:    500,
		Surface:       SurfaceHTTP,
		Retryable:     true,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Internal service error",
		NextAction:    "Retry with backoff; if it persists give your platform administrator the request id {request_id}.",
		Meaning:       "An unexpected internal condition.",
	},
	CodeInvalidIdentifier: {
		Code:          CodeInvalidIdentifier,
		Category:      "request_validation",
		HTTPStatus:    422,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec.dns_names",
		Title:         "Invalid DNS identifier",
		NextAction:    "Correct the DNS name and re-apply; the normalisation step rejected it for {reason}.",
		Meaning:       "A DNS name is not a valid IDNA A-label FQDN under the shared normalisation primitive.",
	},
	CodeInvalidPageToken: {
		Code:          CodeInvalidPageToken,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorClientBug,
		AttributePath: "",
		Title:         "Invalid page token",
		NextAction:    "Restart the listing without a page token; report a repeat to the Terraform provider maintainers.",
		Meaning:       "The continuation token does not match this query, or has expired.",
	},
	CodeInvalidPrincipalID: {
		Code:          CodeInvalidPrincipalID,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Invalid principal id",
		NextAction:    "Supply the principal's Entra object id as the principal query parameter.",
		Meaning:       "GET /v1/exposure was called with no principal, or with a value that is not a well-formed Entra object id.",
	},
	CodeInvalidRekeyReason: {
		Code:          CodeInvalidRekeyReason,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Invalid rekey reason",
		NextAction:    "Send a reason of suspected_key_compromise, scheduled_rotation or personnel_change.",
		Meaning:       "actions/rekey was called with no reason, or a reason outside the three permitted values.",
	},
	CodeInvalidSpec: {
		Code:          CodeInvalidSpec,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec",
		Title:         "Invalid specification",
		NextAction:    "Correct the fields listed in errors[] and re-apply.",
		Meaning:       "One or more spec fields are invalid; the offending fields are listed in errors[].",
	},
	CodeNamespaceNotAuthorised: {
		Code:          CodeNamespaceNotAuthorised,
		Category:      "authorisation",
		HTTPStatus:    403,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Namespace not authorised",
		NextAction:    "Ask your platform administrator for a grant on namespace {namespace}.",
		Meaning:       "The namespace is not granted to this caller, or does not exist. Never 404 (spec section 6.1).",
	},
	CodeNamespaceQuotaExceeded: {
		Code:          CodeNamespaceQuotaExceeded,
		Category:      "rate_limiting",
		HTTPStatus:    429,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Namespace quota exceeded",
		NextAction:    "Ask your platform administrator to raise the {limit_name} limit on namespace {namespace}.",
		Meaning:       "A namespace registration or issuance quota is exhausted.",
	},
	CodeOperationExpired: {
		Code:          CodeOperationExpired,
		Category:      "absence",
		HTTPStatus:    410,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Operation past retention",
		NextAction:    "Fall back to the registration and compare observed_generation against target_generation.",
		Meaning:       "The operation is past its archive retention window.",
	},
	CodeOperationInFlight: {
		Code:          CodeOperationInFlight,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     true,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Operation already in flight",
		NextAction:    "Wait for operation {operation_id} to reach a terminal state, then retry; honour Retry-After.",
		Meaning:       "A non-terminal operation for the registration's current spec hash exists.",
	},
	CodeOperationNotFound: {
		Code:          CodeOperationNotFound,
		Category:      "absence",
		HTTPStatus:    404,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Operation not found",
		NextAction:    "Fall back to the registration and compare observed_generation against target_generation.",
		Meaning:       "Unknown operation id.",
	},
	CodeOperationNotPermitted: {
		Code:          CodeOperationNotPermitted,
		Category:      "authorisation",
		HTTPStatus:    403,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Operation not permitted in this namespace",
		NextAction:    "Ask your platform administrator to add the {operation} operation to this principal's grant on {namespace}.",
		Meaning:       "The caller's grant on the namespace does not permit this operation.",
	},
	CodeOwnershipConflict: {
		Code:          CodeOwnershipConflict,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Registration owned by another principal",
		NextAction:    "Use POST actions/claim to take ownership deliberately, or manage the registration from its owning workspace.",
		Meaning:       "The registration is owned by a different principal.",
	},
	CodeOwnershipTransferRequired: {
		Code:          CodeOwnershipTransferRequired,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Explicit ownership transfer required",
		NextAction:    "Call POST actions/claim with acknowledge_transfer true before importing this registration.",
		Meaning:       "The request would transfer ownership implicitly; an explicit claim is required.",
	},
	CodePolicyUnavailable: {
		Code:          CodePolicyUnavailable,
		Category:      "service_dependency",
		HTTPStatus:    503,
		Surface:       SurfaceHTTP,
		Retryable:     true,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Policy store unavailable",
		NextAction:    "Retry with backoff; if it persists ask your platform administrator to check the policy store.",
		Meaning:       "The policy store is unreachable. All mutating operations are rejected immediately; reads serve last-known-good for at most 300 seconds.",
	},
	CodePreconditionRequired: {
		Code:          CodePreconditionRequired,
		Category:      "conflict_precondition",
		HTTPStatus:    428,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorClientBug,
		AttributePath: "",
		Title:         "Precondition header required",
		NextAction:    "Report to the Terraform provider maintainers; a PUT must carry If-None-Match asterisk or If-Match.",
		Meaning:       "A PUT was sent with neither If-None-Match nor If-Match.",
	},
	CodePrincipalNotBound: {
		Code:          CodePrincipalNotBound,
		Category:      "authorisation",
		HTTPStatus:    403,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Principal not bound",
		NextAction:    "Ask your platform administrator to bind this principal; a recreated managed identity has a new object id.",
		Meaning:       "No enabled, in-date principal binding exists for this object id.",
	},
	CodePublicationRateGuard: {
		Code:          CodePublicationRateGuard,
		Category:      "rate_limiting",
		HTTPStatus:    429,
		Surface:       SurfaceBoth,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Publication rate guard tripped",
		NextAction:    "Stop re-applying and inspect the registration; more than {threshold} versions were published in 24 hours.",
		Meaning:       "More than five published versions for this registration in 24 hours; an issuance loop is suspected.",
	},
	CodeRateLimited: {
		Code:          CodeRateLimited,
		Category:      "rate_limiting",
		HTTPStatus:    429,
		Surface:       SurfaceHTTP,
		Retryable:     true,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Rate limited",
		NextAction:    "Honour Retry-After and retry after {retry_after_seconds} seconds.",
		Meaning:       "The service throttled the request.",
	},
	CodeRegistrationDeleted: {
		Code:          CodeRegistrationDeleted,
		Category:      "absence",
		HTTPStatus:    410,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Registration was deleted",
		NextAction:    "Remove the resource from state; the registration was decommissioned at {deleted_at}.",
		Meaning:       "The registration was decommissioned. The only 410 that may remove a resource from client state.",
	},
	CodeRegistrationExists: {
		Code:          CodeRegistrationExists,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Registration already exists",
		NextAction:    "Import the existing registration with terraform import, then re-apply.",
		Meaning:       "A different registration already occupies namespace/name, or the spec hash differs from the existing one.",
	},
	CodeRegistrationNotFound: {
		Code:          CodeRegistrationNotFound,
		Category:      "absence",
		HTTPStatus:    404,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Registration not found",
		NextAction:    "Remove the resource from state, or create it; it does not exist in namespace {namespace}.",
		Meaning:       "No such registration within an authorised namespace. The only 404 that may remove a resource from client state.",
	},
	CodeRekeyAwaitingConsumerObservation: {
		Code:          CodeRekeyAwaitingConsumerObservation,
		Category:      "compromise_response",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Rekey awaiting consumer observation",
		NextAction:    "Wait for the consumer to pick the new leaf up, or confirm the cut-over window to revoke the predecessor now.",
		Meaning:       "The replacement leaf is published; predecessor revocation is held until the new thumbprint reaches consumer_observed.",
	},
	CodeRekeyPredecessorRevocationFailed: {
		Code:          CodeRekeyPredecessorRevocationFailed,
		Category:      "compromise_response",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     true,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Predecessor revocation failed after rekey",
		NextAction:    "Ask your platform administrator to retry the revocation and verify the predecessor serial's status with the certificate authority.",
		Meaning:       "The replacement is live but the predecessor was not revoked, so a key believed compromised is still valid.",
	},
	CodeRestorePendingAcceptance: {
		Code:          CodeRestorePendingAcceptance,
		Category:      "service_dependency",
		HTTPStatus:    503,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Restore pending acceptance",
		NextAction:    "Ask your platform administrator to verify the restore and call POST /v1/admin/accept-restore.",
		Meaning:       "The epoch fence is raised after a detected restore; the service is in reconciliation-only mode.",
	},
	CodeRoleNotGranted: {
		Code:          CodeRoleNotGranted,
		Category:      "authorisation",
		HTTPStatus:    403,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Required app role not granted",
		NextAction:    "Ask your platform administrator to assign the {required_role} app role to this principal.",
		Meaning:       "The caller lacks the app role the endpoint requires.",
	},
	CodeServiceUnavailable: {
		Code:          CodeServiceUnavailable,
		Category:      "service_dependency",
		HTTPStatus:    503,
		Surface:       SurfaceHTTP,
		Retryable:     true,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Service unavailable",
		NextAction:    "Retry with backoff; if it persists ask your platform administrator to check service health.",
		Meaning:       "The service is temporarily unable to serve the request.",
	},
	CodeSpecImmutableField: {
		Code:          CodeSpecImmutableField,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec",
		Title:         "Read-only or reserved field was set",
		NextAction:    "Remove the read-only or reserved field {field} from the request body and re-apply.",
		Meaning:       "A read-only or reserved field was set by the client.",
	},
	CodeSpecRevisionConflict: {
		Code:          CodeSpecRevisionConflict,
		Category:      "conflict_precondition",
		HTTPStatus:    412,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Specification revision conflict",
		NextAction:    "Run terraform refresh and re-plan; never retry with If-Match asterisk.",
		Meaning:       "The registration changed since the plan was made; the If-Match precondition failed.",
	},
	CodeSubjectNameTooLong: {
		Code:          CodeSubjectNameTooLong,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceBoth,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec.dns_names",
		Title:         "No name short enough to form a subject",
		NextAction:    "Add a DNS name of 64 characters or fewer to the certificate and re-apply.",
		Meaning:       "No DNS name in the set is 64 characters or fewer, so no common name can be formed.",
	},
	CodeTokenAudienceMismatch: {
		Code:          CodeTokenAudienceMismatch,
		Category:      "authentication",
		HTTPStatus:    401,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Token audience mismatch",
		NextAction:    "Set the client's configured audience to {expected_audience} and re-authenticate.",
		Meaning:       "The token `aud` claim is not this service's audience.",
	},
	CodeTokenTenantMismatch: {
		Code:          CodeTokenTenantMismatch,
		Category:      "authentication",
		HTTPStatus:    401,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Token tenant mismatch",
		NextAction:    "Authenticate in tenant {expected_tenant_id} and retry.",
		Meaning:       "The token `tid` claim is not in the allowed tenant set.",
	},
	CodeTooManyIdentifiers: {
		Code:          CodeTooManyIdentifiers,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec.dns_names",
		Title:         "Too many identifiers",
		NextAction:    "Split the certificate; this profile and namespace permit at most {max_identifiers} names.",
		Meaning:       "The request names more identifiers than the ACME profile or the namespace permits.",
	},
	CodeUnacceptableMediaType: {
		Code:          CodeUnacceptableMediaType,
		Category:      "request_validation",
		HTTPStatus:    406,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorClientBug,
		AttributePath: "",
		Title:         "Unacceptable media type",
		NextAction:    "Send Accept application/json; report a repeat to the Terraform provider maintainers.",
		Meaning:       "The Accept header did not permit application/json.",
	},
	CodeUnauthenticated: {
		Code:          CodeUnauthenticated,
		Category:      "authentication",
		HTTPStatus:    401,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Not authenticated",
		NextAction:    "Check the credential method the provider actually used, then re-authenticate and retry.",
		Meaning:       "No usable token was presented.",
	},
	CodeUnsupportedFeature: {
		Code:          CodeUnsupportedFeature,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Feature not available on this service instance",
		NextAction:    "Ask your platform administrator to upgrade the service to at least {minimum_service_version}, which advertises {feature}.",
		Meaning:       "The request uses a feature this service instance does not advertise.",
	},
	CodeUnsupportedKeyType: {
		Code:          CodeUnsupportedKeyType,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec.key",
		Title:         "Unsupported key type",
		NextAction:    "Choose a key policy this service enables; see key_policies in GET /v1/capabilities.",
		Meaning:       "The requested key type is not enabled. RSA-HSM, EC-HSM and Managed HSM destinations are rejected unconditionally.",
	},
	CodeValidationBindingAmbiguous: {
		Code:          CodeValidationBindingAmbiguous,
		Category:      "request_validation",
		HTTPStatus:    400,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorCaller,
		AttributePath: "spec.validation_binding",
		Title:         "Validation binding is ambiguous",
		NextAction:    "Set spec.validation_binding to one of {candidates} and re-apply.",
		Meaning:       "More than one validation binding could serve these names.",
	},
	CodeValidationBindingNotAuthorised: {
		Code:          CodeValidationBindingNotAuthorised,
		Category:      "authorisation",
		HTTPStatus:    403,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "spec.validation_binding",
		Title:         "Validation binding not authorised",
		NextAction:    "Ask your platform administrator to grant validation binding {validation_binding} to namespace {namespace}.",
		Meaning:       "The named validation binding is not available to this namespace.",
	},
	CodeValidationBindingUnhealthy: {
		Code:          CodeValidationBindingUnhealthy,
		Category:      "conflict_precondition",
		HTTPStatus:    409,
		Surface:       SurfaceHTTP,
		Retryable:     true,
		Actor:         ActorDNSOwner,
		AttributePath: "spec.validation_binding",
		Title:         "Validation binding unhealthy",
		NextAction:    "Ask the DNS zone owner to create CNAME {required_cname} pointing at {required_target}, then retry.",
		Meaning:       "The validation binding's preflight probe is failing.",
	},
	CodeValidationBudgetExhausted: {
		Code:          CodeValidationBudgetExhausted,
		Category:      "rate_limiting",
		HTTPStatus:    429,
		Surface:       SurfaceBoth,
		Retryable:     true,
		Actor:         ActorCaller,
		AttributePath: "",
		Title:         "Validation budget exhausted",
		NextAction:    "Fix the DNS delegation for {hostname} before retrying; failed validations consume the budget.",
		Meaning:       "The failed-validation budget for this hostname is exhausted.",
	},
	CodeVerifyAlgorithmMismatch: {
		Code:          CodeVerifyAlgorithmMismatch,
		Category:      "prepublication_verification",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Issued leaf algorithm disagrees with policy",
		NextAction:    "Ask your platform administrator to investigate; nothing was published and the current certificate is untouched.",
		Meaning:       "Key type, size or signature algorithm disagrees with the policy.",
	},
	CodeVerifyChainUntrusted: {
		Code:          CodeVerifyChainUntrusted,
		Category:      "prepublication_verification",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Issued chain does not build to a pinned root",
		NextAction:    "Ask your platform administrator to check the pinned trust bundle; a rate of this across registrations must page.",
		Meaning:       "The chain does not build to a root in the pinned trust bundle.",
	},
	CodeVerifyMalformedChain: {
		Code:          CodeVerifyMalformedChain,
		Category:      "prepublication_verification",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Issued chain is malformed",
		NextAction:    "Ask your platform administrator to investigate; nothing was published and the current certificate is untouched.",
		Meaning:       "The chain does not parse as X.509 v3, or is empty, or is not leaf-first.",
	},
	CodeVerifyPendingOperationRotated: {
		Code:          CodeVerifyPendingOperationRotated,
		Category:      "prepublication_verification",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     true,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Key Vault pending operation was rotated",
		NextAction:    "Ask your platform administrator to check for a second writer on this vault object; the service retries with a fresh request.",
		Meaning:       "The Key Vault pending operation's request id no longer matches the recorded one.",
	},
	CodeVerifyPublicKeyMismatch: {
		Code:          CodeVerifyPublicKeyMismatch,
		Category:      "prepublication_verification",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Issued leaf does not match the request key",
		NextAction:    "Ask your platform administrator to investigate; nothing was published and the current certificate is untouched.",
		Meaning:       "The leaf's subject public key does not match the certificate signing request's.",
	},
	CodeVerifyPublishReadbackMismatch: {
		Code:          CodeVerifyPublishReadbackMismatch,
		Category:      "prepublication_verification",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     true,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Post-publication read-back mismatch",
		NextAction:    "Ask your platform administrator to check for a second writer on this vault object; the service retries the read-back.",
		Meaning:       "Post-merge read-back did not return the expected leaf.",
	},
	CodeVerifySanMismatch: {
		Code:          CodeVerifySanMismatch,
		Category:      "prepublication_verification",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Issued leaf SAN set does not match the specification",
		NextAction:    "Ask your platform administrator to investigate; a rate of this across registrations means the certificate authority changed something.",
		Meaning:       "The leaf's dNSName SAN set is not exactly equal to spec.dns_names.",
	},
	CodeVerifyStaleSpecification: {
		Code:          CodeVerifyStaleSpecification,
		Category:      "prepublication_verification",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Pending operation is against a stale specification",
		NextAction:    "Ask your platform administrator to investigate if this repeats; the operation is superseded and a fresh one runs.",
		Meaning:       "The spec revision recorded with the pending operation is no longer current.",
	},
	CodeVerifySubjectNotInSan: {
		Code:          CodeVerifySubjectNotInSan,
		Category:      "prepublication_verification",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Issued leaf subject is not in its SAN set",
		NextAction:    "Ask your platform administrator to investigate; nothing was published and the current certificate is untouched.",
		Meaning:       "The leaf's common name is not a member of its SAN set.",
	},
	CodeVerifyUsageMismatch: {
		Code:          CodeVerifyUsageMismatch,
		Category:      "prepublication_verification",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Issued leaf key usage disagrees with policy",
		NextAction:    "Ask your platform administrator to investigate; nothing was published and the current certificate is untouched.",
		Meaning:       "Extended key usage, basic constraints or key usage disagree with the policy.",
	},
	CodeVerifyValidityWindow: {
		Code:          CodeVerifyValidityWindow,
		Category:      "prepublication_verification",
		HTTPStatus:    0,
		Surface:       SurfaceOp,
		Retryable:     true,
		Actor:         ActorPlatformAdmin,
		AttributePath: "",
		Title:         "Issued leaf validity window is out of range",
		NextAction:    "Ask your platform administrator to check clock skew between the service and the storage account, then retry.",
		Meaning:       "not_before or not_after fall outside the accepted window, measured against the storage clock.",
	},
	CodeWildcardNotAuthorised: {
		Code:          CodeWildcardNotAuthorised,
		Category:      "authorisation",
		HTTPStatus:    403,
		Surface:       SurfaceHTTP,
		Retryable:     false,
		Actor:         ActorPlatformAdmin,
		AttributePath: "spec.dns_names",
		Title:         "Wildcard not authorised",
		NextAction:    "Ask your platform administrator for an explicit wildcard authorisation on {base}; a subtree grant never implies one.",
		Meaning:       "A wildcard identifier requires an explicit wildcard authorisation; it is never inferred from a subtree grant.",
	},
}

// Lookup returns the metadata for a code. An UNKNOWN code is not an error: a client
// meeting a code added by a newer service renders NextAction, Title, Detail and the
// request id from the response verbatim and treats it as non-retryable.
func Lookup(code Code) (Metadata, bool) {
	meta, found := metadata[code]
	return meta, found
}

// AllCodes returns every published code, in a stable order.
func AllCodes() []Code {
	out := make([]Code, 0, len(codeOrder))
	out = append(out, codeOrder...)
	return out
}

var codeOrder = []Code{
	CodeAcknowledgementRequired,
	CodeACMEAuthorisationExpired,
	CodeACMEChallengeFailed,
	CodeACMEError,
	CodeACMEOrderInvalid,
	CodeACMERateLimited,
	CodeAPIVersionUnsupported,
	CodeAuthorisationDenied,
	CodeAuthorisationRevoked,
	CodeCAALookupFailed,
	CodeCAAProhibited,
	CodeCatalogueSchemaTooNew,
	CodeClientTooOld,
	CodeDeletionPolicyConflict,
	CodeDeletionPolicyNotPermitted,
	CodeDependencyUnavailable,
	CodeDestinationAccessDenied,
	CodeDestinationAmbiguous,
	CodeDestinationHasCompetingIssuer,
	CodeDestinationIncompatibleWithConsumer,
	CodeDestinationNotAuthorised,
	CodeDestinationNotManaged,
	CodeDestinationOwnedByAnotherServiceInstance,
	CodeDestinationOwnedElsewhere,
	CodeDestinationPendingOperationConflict,
	CodeDestinationRacedByAnotherWriter,
	CodeDestinationRecentlyPublished,
	CodeDestinationRetainedByTombstone,
	CodeDestinationShared,
	CodeDestinationSoftDeleted,
	CodeDestinationUnreachable,
	CodeDNSCnameLoop,
	CodeDNSDelegationMismatch,
	CodeDNSPropagationTimeout,
	CodeDNSRecordSetContention,
	CodeDNSRecordSetFull,
	CodeDnssecValidationFailure,
	CodeDomainNotAuthorised,
	CodeExposureInventoryIncomplete,
	CodeInternalError,
	CodeInvalidIdentifier,
	CodeInvalidPageToken,
	CodeInvalidPrincipalID,
	CodeInvalidRekeyReason,
	CodeInvalidSpec,
	CodeNamespaceNotAuthorised,
	CodeNamespaceQuotaExceeded,
	CodeOperationExpired,
	CodeOperationInFlight,
	CodeOperationNotFound,
	CodeOperationNotPermitted,
	CodeOwnershipConflict,
	CodeOwnershipTransferRequired,
	CodePolicyUnavailable,
	CodePreconditionRequired,
	CodePrincipalNotBound,
	CodePublicationRateGuard,
	CodeRateLimited,
	CodeRegistrationDeleted,
	CodeRegistrationExists,
	CodeRegistrationNotFound,
	CodeRekeyAwaitingConsumerObservation,
	CodeRekeyPredecessorRevocationFailed,
	CodeRestorePendingAcceptance,
	CodeRoleNotGranted,
	CodeServiceUnavailable,
	CodeSpecImmutableField,
	CodeSpecRevisionConflict,
	CodeSubjectNameTooLong,
	CodeTokenAudienceMismatch,
	CodeTokenTenantMismatch,
	CodeTooManyIdentifiers,
	CodeUnacceptableMediaType,
	CodeUnauthenticated,
	CodeUnsupportedFeature,
	CodeUnsupportedKeyType,
	CodeValidationBindingAmbiguous,
	CodeValidationBindingNotAuthorised,
	CodeValidationBindingUnhealthy,
	CodeValidationBudgetExhausted,
	CodeVerifyAlgorithmMismatch,
	CodeVerifyChainUntrusted,
	CodeVerifyMalformedChain,
	CodeVerifyPendingOperationRotated,
	CodeVerifyPublicKeyMismatch,
	CodeVerifyPublishReadbackMismatch,
	CodeVerifySanMismatch,
	CodeVerifyStaleSpecification,
	CodeVerifySubjectNotInSan,
	CodeVerifyUsageMismatch,
	CodeVerifyValidityWindow,
	CodeWildcardNotAuthorised,
}

// Sentinel errors, so a caller can use errors.Is against a published code.
var (
	ErrAcknowledgementRequired                  = errors.New("acknowledgement_required")
	ErrACMEAuthorisationExpired                 = errors.New("acme_authorisation_expired")
	ErrACMEChallengeFailed                      = errors.New("acme_challenge_failed")
	ErrACMEError                                = errors.New("acme_error")
	ErrACMEOrderInvalid                         = errors.New("acme_order_invalid")
	ErrACMERateLimited                          = errors.New("acme_rate_limited")
	ErrAPIVersionUnsupported                    = errors.New("api_version_unsupported")
	ErrAuthorisationDenied                      = errors.New("authorisation_denied")
	ErrAuthorisationRevoked                     = errors.New("authorisation_revoked")
	ErrCAALookupFailed                          = errors.New("caa_lookup_failed")
	ErrCAAProhibited                            = errors.New("caa_prohibited")
	ErrCatalogueSchemaTooNew                    = errors.New("catalogue_schema_too_new")
	ErrClientTooOld                             = errors.New("client_too_old")
	ErrDeletionPolicyConflict                   = errors.New("deletion_policy_conflict")
	ErrDeletionPolicyNotPermitted               = errors.New("deletion_policy_not_permitted")
	ErrDependencyUnavailable                    = errors.New("dependency_unavailable")
	ErrDestinationAccessDenied                  = errors.New("destination_access_denied")
	ErrDestinationAmbiguous                     = errors.New("destination_ambiguous")
	ErrDestinationHasCompetingIssuer            = errors.New("destination_has_competing_issuer")
	ErrDestinationIncompatibleWithConsumer      = errors.New("destination_incompatible_with_consumer")
	ErrDestinationNotAuthorised                 = errors.New("destination_not_authorised")
	ErrDestinationNotManaged                    = errors.New("destination_not_managed")
	ErrDestinationOwnedByAnotherServiceInstance = errors.New("destination_owned_by_another_service_instance")
	ErrDestinationOwnedElsewhere                = errors.New("destination_owned_elsewhere")
	ErrDestinationPendingOperationConflict      = errors.New("destination_pending_operation_conflict")
	ErrDestinationRacedByAnotherWriter          = errors.New("destination_raced_by_another_writer")
	ErrDestinationRecentlyPublished             = errors.New("destination_recently_published")
	ErrDestinationRetainedByTombstone           = errors.New("destination_retained_by_tombstone")
	ErrDestinationShared                        = errors.New("destination_shared")
	ErrDestinationSoftDeleted                   = errors.New("destination_soft_deleted")
	ErrDestinationUnreachable                   = errors.New("destination_unreachable")
	ErrDNSCnameLoop                             = errors.New("dns_cname_loop")
	ErrDNSDelegationMismatch                    = errors.New("dns_delegation_mismatch")
	ErrDNSPropagationTimeout                    = errors.New("dns_propagation_timeout")
	ErrDNSRecordSetContention                   = errors.New("dns_record_set_contention")
	ErrDNSRecordSetFull                         = errors.New("dns_record_set_full")
	ErrDnssecValidationFailure                  = errors.New("dnssec_validation_failure")
	ErrDomainNotAuthorised                      = errors.New("domain_not_authorised")
	ErrExposureInventoryIncomplete              = errors.New("exposure_inventory_incomplete")
	ErrInternalError                            = errors.New("internal_error")
	ErrInvalidIdentifier                        = errors.New("invalid_identifier")
	ErrInvalidPageToken                         = errors.New("invalid_page_token")
	ErrInvalidPrincipalID                       = errors.New("invalid_principal_id")
	ErrInvalidRekeyReason                       = errors.New("invalid_rekey_reason")
	ErrInvalidSpec                              = errors.New("invalid_spec")
	ErrNamespaceNotAuthorised                   = errors.New("namespace_not_authorised")
	ErrNamespaceQuotaExceeded                   = errors.New("namespace_quota_exceeded")
	ErrOperationExpired                         = errors.New("operation_expired")
	ErrOperationInFlight                        = errors.New("operation_in_flight")
	ErrOperationNotFound                        = errors.New("operation_not_found")
	ErrOperationNotPermitted                    = errors.New("operation_not_permitted")
	ErrOwnershipConflict                        = errors.New("ownership_conflict")
	ErrOwnershipTransferRequired                = errors.New("ownership_transfer_required")
	ErrPolicyUnavailable                        = errors.New("policy_unavailable")
	ErrPreconditionRequired                     = errors.New("precondition_required")
	ErrPrincipalNotBound                        = errors.New("principal_not_bound")
	ErrPublicationRateGuard                     = errors.New("publication_rate_guard")
	ErrRateLimited                              = errors.New("rate_limited")
	ErrRegistrationDeleted                      = errors.New("registration_deleted")
	ErrRegistrationExists                       = errors.New("registration_exists")
	ErrRegistrationNotFound                     = errors.New("registration_not_found")
	ErrRekeyAwaitingConsumerObservation         = errors.New("rekey_awaiting_consumer_observation")
	ErrRekeyPredecessorRevocationFailed         = errors.New("rekey_predecessor_revocation_failed")
	ErrRestorePendingAcceptance                 = errors.New("restore_pending_acceptance")
	ErrRoleNotGranted                           = errors.New("role_not_granted")
	ErrServiceUnavailable                       = errors.New("service_unavailable")
	ErrSpecImmutableField                       = errors.New("spec_immutable_field")
	ErrSpecRevisionConflict                     = errors.New("spec_revision_conflict")
	ErrSubjectNameTooLong                       = errors.New("subject_name_too_long")
	ErrTokenAudienceMismatch                    = errors.New("token_audience_mismatch")
	ErrTokenTenantMismatch                      = errors.New("token_tenant_mismatch")
	ErrTooManyIdentifiers                       = errors.New("too_many_identifiers")
	ErrUnacceptableMediaType                    = errors.New("unacceptable_media_type")
	ErrUnauthenticated                          = errors.New("unauthenticated")
	ErrUnsupportedFeature                       = errors.New("unsupported_feature")
	ErrUnsupportedKeyType                       = errors.New("unsupported_key_type")
	ErrValidationBindingAmbiguous               = errors.New("validation_binding_ambiguous")
	ErrValidationBindingNotAuthorised           = errors.New("validation_binding_not_authorised")
	ErrValidationBindingUnhealthy               = errors.New("validation_binding_unhealthy")
	ErrValidationBudgetExhausted                = errors.New("validation_budget_exhausted")
	ErrVerifyAlgorithmMismatch                  = errors.New("verify_algorithm_mismatch")
	ErrVerifyChainUntrusted                     = errors.New("verify_chain_untrusted")
	ErrVerifyMalformedChain                     = errors.New("verify_malformed_chain")
	ErrVerifyPendingOperationRotated            = errors.New("verify_pending_operation_rotated")
	ErrVerifyPublicKeyMismatch                  = errors.New("verify_public_key_mismatch")
	ErrVerifyPublishReadbackMismatch            = errors.New("verify_publish_readback_mismatch")
	ErrVerifySanMismatch                        = errors.New("verify_san_mismatch")
	ErrVerifyStaleSpecification                 = errors.New("verify_stale_specification")
	ErrVerifySubjectNotInSan                    = errors.New("verify_subject_not_in_san")
	ErrVerifyUsageMismatch                      = errors.New("verify_usage_mismatch")
	ErrVerifyValidityWindow                     = errors.New("verify_validity_window")
	ErrWildcardNotAuthorised                    = errors.New("wildcard_not_authorised")
)

// Sentinel returns the sentinel error for a code, or nil when the code is unknown.
func Sentinel(code Code) error {
	return sentinels[code]
}

var sentinels = map[Code]error{
	CodeAcknowledgementRequired:                  ErrAcknowledgementRequired,
	CodeACMEAuthorisationExpired:                 ErrACMEAuthorisationExpired,
	CodeACMEChallengeFailed:                      ErrACMEChallengeFailed,
	CodeACMEError:                                ErrACMEError,
	CodeACMEOrderInvalid:                         ErrACMEOrderInvalid,
	CodeACMERateLimited:                          ErrACMERateLimited,
	CodeAPIVersionUnsupported:                    ErrAPIVersionUnsupported,
	CodeAuthorisationDenied:                      ErrAuthorisationDenied,
	CodeAuthorisationRevoked:                     ErrAuthorisationRevoked,
	CodeCAALookupFailed:                          ErrCAALookupFailed,
	CodeCAAProhibited:                            ErrCAAProhibited,
	CodeCatalogueSchemaTooNew:                    ErrCatalogueSchemaTooNew,
	CodeClientTooOld:                             ErrClientTooOld,
	CodeDeletionPolicyConflict:                   ErrDeletionPolicyConflict,
	CodeDeletionPolicyNotPermitted:               ErrDeletionPolicyNotPermitted,
	CodeDependencyUnavailable:                    ErrDependencyUnavailable,
	CodeDestinationAccessDenied:                  ErrDestinationAccessDenied,
	CodeDestinationAmbiguous:                     ErrDestinationAmbiguous,
	CodeDestinationHasCompetingIssuer:            ErrDestinationHasCompetingIssuer,
	CodeDestinationIncompatibleWithConsumer:      ErrDestinationIncompatibleWithConsumer,
	CodeDestinationNotAuthorised:                 ErrDestinationNotAuthorised,
	CodeDestinationNotManaged:                    ErrDestinationNotManaged,
	CodeDestinationOwnedByAnotherServiceInstance: ErrDestinationOwnedByAnotherServiceInstance,
	CodeDestinationOwnedElsewhere:                ErrDestinationOwnedElsewhere,
	CodeDestinationPendingOperationConflict:      ErrDestinationPendingOperationConflict,
	CodeDestinationRacedByAnotherWriter:          ErrDestinationRacedByAnotherWriter,
	CodeDestinationRecentlyPublished:             ErrDestinationRecentlyPublished,
	CodeDestinationRetainedByTombstone:           ErrDestinationRetainedByTombstone,
	CodeDestinationShared:                        ErrDestinationShared,
	CodeDestinationSoftDeleted:                   ErrDestinationSoftDeleted,
	CodeDestinationUnreachable:                   ErrDestinationUnreachable,
	CodeDNSCnameLoop:                             ErrDNSCnameLoop,
	CodeDNSDelegationMismatch:                    ErrDNSDelegationMismatch,
	CodeDNSPropagationTimeout:                    ErrDNSPropagationTimeout,
	CodeDNSRecordSetContention:                   ErrDNSRecordSetContention,
	CodeDNSRecordSetFull:                         ErrDNSRecordSetFull,
	CodeDnssecValidationFailure:                  ErrDnssecValidationFailure,
	CodeDomainNotAuthorised:                      ErrDomainNotAuthorised,
	CodeExposureInventoryIncomplete:              ErrExposureInventoryIncomplete,
	CodeInternalError:                            ErrInternalError,
	CodeInvalidIdentifier:                        ErrInvalidIdentifier,
	CodeInvalidPageToken:                         ErrInvalidPageToken,
	CodeInvalidPrincipalID:                       ErrInvalidPrincipalID,
	CodeInvalidRekeyReason:                       ErrInvalidRekeyReason,
	CodeInvalidSpec:                              ErrInvalidSpec,
	CodeNamespaceNotAuthorised:                   ErrNamespaceNotAuthorised,
	CodeNamespaceQuotaExceeded:                   ErrNamespaceQuotaExceeded,
	CodeOperationExpired:                         ErrOperationExpired,
	CodeOperationInFlight:                        ErrOperationInFlight,
	CodeOperationNotFound:                        ErrOperationNotFound,
	CodeOperationNotPermitted:                    ErrOperationNotPermitted,
	CodeOwnershipConflict:                        ErrOwnershipConflict,
	CodeOwnershipTransferRequired:                ErrOwnershipTransferRequired,
	CodePolicyUnavailable:                        ErrPolicyUnavailable,
	CodePreconditionRequired:                     ErrPreconditionRequired,
	CodePrincipalNotBound:                        ErrPrincipalNotBound,
	CodePublicationRateGuard:                     ErrPublicationRateGuard,
	CodeRateLimited:                              ErrRateLimited,
	CodeRegistrationDeleted:                      ErrRegistrationDeleted,
	CodeRegistrationExists:                       ErrRegistrationExists,
	CodeRegistrationNotFound:                     ErrRegistrationNotFound,
	CodeRekeyAwaitingConsumerObservation:         ErrRekeyAwaitingConsumerObservation,
	CodeRekeyPredecessorRevocationFailed:         ErrRekeyPredecessorRevocationFailed,
	CodeRestorePendingAcceptance:                 ErrRestorePendingAcceptance,
	CodeRoleNotGranted:                           ErrRoleNotGranted,
	CodeServiceUnavailable:                       ErrServiceUnavailable,
	CodeSpecImmutableField:                       ErrSpecImmutableField,
	CodeSpecRevisionConflict:                     ErrSpecRevisionConflict,
	CodeSubjectNameTooLong:                       ErrSubjectNameTooLong,
	CodeTokenAudienceMismatch:                    ErrTokenAudienceMismatch,
	CodeTokenTenantMismatch:                      ErrTokenTenantMismatch,
	CodeTooManyIdentifiers:                       ErrTooManyIdentifiers,
	CodeUnacceptableMediaType:                    ErrUnacceptableMediaType,
	CodeUnauthenticated:                          ErrUnauthenticated,
	CodeUnsupportedFeature:                       ErrUnsupportedFeature,
	CodeUnsupportedKeyType:                       ErrUnsupportedKeyType,
	CodeValidationBindingAmbiguous:               ErrValidationBindingAmbiguous,
	CodeValidationBindingNotAuthorised:           ErrValidationBindingNotAuthorised,
	CodeValidationBindingUnhealthy:               ErrValidationBindingUnhealthy,
	CodeValidationBudgetExhausted:                ErrValidationBudgetExhausted,
	CodeVerifyAlgorithmMismatch:                  ErrVerifyAlgorithmMismatch,
	CodeVerifyChainUntrusted:                     ErrVerifyChainUntrusted,
	CodeVerifyMalformedChain:                     ErrVerifyMalformedChain,
	CodeVerifyPendingOperationRotated:            ErrVerifyPendingOperationRotated,
	CodeVerifyPublicKeyMismatch:                  ErrVerifyPublicKeyMismatch,
	CodeVerifyPublishReadbackMismatch:            ErrVerifyPublishReadbackMismatch,
	CodeVerifySanMismatch:                        ErrVerifySanMismatch,
	CodeVerifyStaleSpecification:                 ErrVerifyStaleSpecification,
	CodeVerifySubjectNotInSan:                    ErrVerifySubjectNotInSan,
	CodeVerifyUsageMismatch:                      ErrVerifyUsageMismatch,
	CodeVerifyValidityWindow:                     ErrVerifyValidityWindow,
	CodeWildcardNotAuthorised:                    ErrWildcardNotAuthorised,
}

// RetiredCodeCount is the number of codes withdrawn from service. The names themselves
// live in contracts/errors/error-codes.yaml and are deliberately NOT materialised here:
// a repository-wide grep forbids those strings, and a client never needs to recognise a
// name the service never sends.
const RetiredCodeCount = 1
