// Code generated by contracts/tools/generate.py v1.0.0 from contracts/api/openapi.yaml; DO NOT EDIT.
//
// Edit contracts/api/openapi.yaml and run `make contracts-generate`. Hand edits are reverted by the
// drift check in `make contracts-verify`.

package contracts

import "encoding/json"

// Health
type Health struct {
	Status string `json:"status"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// Problem -- RFC 9457 `application/problem+json`, returned for EVERY non-2xx. `code` is the
// machine-readable contract; clients branch on `code` alone, never on `status`, never on
// `title` or `detail` text. A client meeting an UNKNOWN code still renders `next_action` from
// the response, so forward compatibility does not cost actionability.
type Problem struct {
	// Who can act. Rendered verbatim if unknown to the client; new actors may be added.
	Actor string `json:"actor"`
	// A code from `contracts/errors/error-codes.yaml`. snake_case, UK spelling. Immutable once
	// published. The schema does not enumerate the codes, because a client MUST tolerate a code
	// added by a newer service.
	Code string `json:"code"`
	// From a fixed catalogue of templated strings. Never an exception's `str()`, never a stack
	// trace, never a blob path, never an ACME order, authorisation or challenge URL.
	Detail *string `json:"detail,omitempty"`
	// Per-field subproblems.
	Errors []ProblemFieldError `json:"errors,omitempty"`
	// The request path this problem describes.
	Instance *string `json:"instance,omitempty"`
	// Imperative and non-empty. When `actor` is not `caller` it names the party to ask.
	NextAction string `json:"next_action"`
	// Present ONLY when the caller already holds `Certificates.Read` on the namespace in question
	// and could therefore already enumerate the same data. The non-enumeration rule buys nothing
	// against a caller who can already enumerate, and costs a round trip on every onboarding.
	Permitted map[string]json.RawMessage `json:"permitted,omitempty"`
	// The policy revision the denial was evaluated against.
	PolicyRevision *int64 `json:"policy_revision,omitempty"`
	// Where to request the missing grant. Same precondition as `permitted`.
	RequestAccessAt *string `json:"request_access_at,omitempty"`
	// The caller's `X-Request-Id`, so a support request is one log query.
	RequestID string `json:"request_id"`
	// Seconds, mirroring the `Retry-After` header where one is sent.
	RetryAfter *int64 `json:"retry_after,omitempty"`
	// AUTHORITATIVE for the client's retry classifier. The status fallback is used only when the
	// body does not parse, and it retries `408`, `429`, `500`, `502`, `503`, `504`, transport
	// errors, and `409` WHEN ACCOMPANIED BY `Retry-After`.
	Retryable bool `json:"retryable"`
	// MANDATORY on every `404` and `410`, because it is one of the four conditions the client
	// requires before removing a resource from state.
	ServiceInstanceID *string `json:"service_instance_id,omitempty"`
	Status            int64   `json:"status"`
	// Short, human-readable, stable per code. Never branched on.
	Title string `json:"title"`
	// `https://mantisec.dev/acme/errors/{code}`.
	Type string `json:"type"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// ProblemFieldError
type ProblemFieldError struct {
	Code string `json:"code"`
	// A dotted WIRE path, such as `spec.dns_names` or `spec.destination.key_vault_id`.
	Field   string `json:"field"`
	Message string `json:"message"`
	// The offending value. For `Set`-typed `dns_names` indices are meaningless in Terraform, so
	// the server sends the value and the client resolves the attribute path from it.
	Value *json.RawMessage `json:"value,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// Warning
type Warning struct {
	Code    string  `json:"code"`
	Field   *string `json:"field,omitempty"`
	Message string  `json:"message"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// Links
type Links struct {
	// The in-flight operation, when there is one.
	Operation *string `json:"operation,omitempty"`
	Self      string  `json:"self"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// Capabilities
type Capabilities struct {
	Caller  CallerIdentity      `json:"caller"`
	Service ServiceCapabilities `json:"service"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// ServiceCapabilities
type ServiceCapabilities struct {
	ACME                 AcmeCapabilities           `json:"acme"`
	APIVersion           string                     `json:"api_version"`
	APIVersionsSupported []string                   `json:"api_versions_supported"`
	Build                map[string]json.RawMessage `json:"build,omitempty"`
	// Reported but NOT part of the client's compatibility check — the client never reads the
	// catalogue. A service build MUST refuse to start if the catalogue schema version is higher
	// than it supports.
	CatalogueSchemaVersion   int64             `json:"catalogue_schema_version"`
	ConsumerProfiles         []ConsumerProfile `json:"consumer_profiles"`
	DeprecatedClientDeadline *string           `json:"deprecated_client_deadline,omitempty"`
	DeprecatedClientVersion  *string           `json:"deprecated_client_version,omitempty"`
	// FEATURE GATING IS BY NAME, NEVER BY VERSION ARITHMETIC. A client wanting
	// `destination_migration` checks for the string here, not for `api_version >= 1.6`. Unknown
	// entries are ignored.
	Features []string `json:"features"`
	// A ULID generated ONCE by the service on first start. It is DATA, NOT CONFIGURATION. It
	// survives redeploying the package, slot swaps, scaling, host replacement, moving to a new
	// Function App with the same storage, ACME account rotation, and restoring a backup. It
	// changes only when the catalogue storage account changes. It is NEVER derived from
	// `instance_name`, the Function App resource id, the hostname or the package: a rename would
	// change an id that must not change, and two deployments sharing a name would collide.
	InstanceID string `json:"instance_id"`
	// A human-readable label from a module variable. A DIFFERENT FIELD from `instance_id`; the two
	// MUST NOT be conflated.
	InstanceName string      `json:"instance_name"`
	KeyPolicies  KeyPolicies `json:"key_policies"`
	Limits       Limits      `json:"limits"`
	// MUST NOT be raised to a version that was not published as `deprecated_client_version` at
	// least 90 days earlier. Raising it hard-errors every consumer workspace in the organisation
	// on its next plan.
	MinimumClientVersion string  `json:"minimum_client_version"`
	PublisherClientID    *string `json:"publisher_client_id,omitempty"`
	// The publishing identity every application team must grant `Key Vault Certificates Officer`
	// on their own vault. Published here so the secure path is the easy path and no documentation
	// needs a `terraform_remote_state` against the platform state.
	PublisherPrincipalID *string `json:"publisher_principal_id,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// AcmeCapabilities
type AcmeCapabilities struct {
	DefaultProfile string `json:"default_profile"`
	DirectoryURL   string `json:"directory_url"`
	// `force-renew` is HARD-DISABLED when this is `production`.
	Environment string                       `json:"environment"`
	Profiles    []map[string]json.RawMessage `json:"profiles"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// Limits
type Limits struct {
	MaxDNSNames        *int64 `json:"max_dns_names,omitempty"`
	MaxLabelKeyBytes   *int64 `json:"max_label_key_bytes,omitempty"`
	MaxLabelValueBytes *int64 `json:"max_label_value_bytes,omitempty"`
	MaxLabels          *int64 `json:"max_labels,omitempty"`
	MaxPageSize        *int64 `json:"max_page_size,omitempty"`
	MaxProbeEndpoints  *int64 `json:"max_probe_endpoints,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// KeyPolicies -- Advertises what is ENABLED, not what the schema can express. In v1
// `algorithms` is `["RSA"]` and `curves` is empty, so the client rejects EC at plan time with a
// good message and ENABLING EC LATER IS A SERVICE POLICY CHANGE, NOT A PROVIDER RELEASE.
type KeyPolicies struct {
	Algorithms []string `json:"algorithms,omitempty"`
	Curves     []string `json:"curves,omitempty"`
	Exportable []bool   `json:"exportable,omitempty"`
	RSASizes   []int64  `json:"rsa_sizes,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// ConsumerProfile -- Carries the per-consumer pickup windows so alert thresholds and the
// `expected_pickup` default are service configuration rather than client constants. The windows
// differ by two orders of magnitude.
type ConsumerProfile struct {
	ExpectedPickup     *string `json:"expected_pickup,omitempty"`
	Name               string  `json:"name"`
	RequiresExportable bool    `json:"requires_exportable"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// CallerIdentity -- What lets the client compare the caller against
// `status.ownership.owner_principal_id` and refuse an import that would silently move
// management to a different principal.
type CallerIdentity struct {
	DisplayName   *string  `json:"display_name,omitempty"`
	Namespaces    []string `json:"namespaces"`
	PrincipalID   string   `json:"principal_id"`
	PrincipalType string   `json:"principal_type"`
	Roles         []string `json:"roles"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// NamespaceCollection
type NamespaceCollection struct {
	Items         []NamespaceSummary `json:"items"`
	NextPageToken *string            `json:"next_page_token,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// NamespaceSummary
type NamespaceSummary struct {
	CallerRoles []string                   `json:"caller_roles"`
	Enabled     bool                       `json:"enabled"`
	Links       map[string]json.RawMessage `json:"links,omitempty"`
	Namespace   string                     `json:"namespace"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// NamespaceDetail -- Exists to move authorisation failures from apply time to plan time.
// Without it the only feedback channel for a wrong namespace, an unapproved domain, a forbidden
// wildcard or a non-permitted destination is a `403` after `terraform apply` has begun changing
// things.
type NamespaceDetail struct {
	AllowedDeletionPolicies      []DeletionPolicy        `json:"allowed_deletion_policies"`
	AllowedKeyPolicies           []AllowedKeyPolicy      `json:"allowed_key_policies"`
	CallerRoles                  []string                `json:"caller_roles"`
	DefaultDeletionPolicy        DeletionPolicy          `json:"default_deletion_policy"`
	Enabled                      bool                    `json:"enabled"`
	MaxIdentifiersPerCertificate int64                   `json:"max_identifiers_per_certificate"`
	Namespace                    string                  `json:"namespace"`
	PermittedDestinations        []DestinationPolicyView `json:"permitted_destinations"`
	// The three match kinds, and only these three. THE POLICY SCHEMA HAS NO FIELD THAT ACCEPTS A
	// PATTERN LANGUAGE FOR IDENTIFIERS: a regex in a hostname matcher is a recurring source of
	// authorisation bypass.
	PermittedDomains []DomainRuleView `json:"permitted_domains"`
	PolicyRevision   int64            `json:"policy_revision"`
	// Wildcard is its own axis and is NEVER inferred from a name-scope grant. DNS-01 for
	// `*.api.example.com` and for `api.example.com` uses the SAME challenge name, so technical
	// control of the zone proves nothing that distinguishes them.
	WildcardPolicy map[string]json.RawMessage `json:"wildcard_policy"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// DomainRuleView
type DomainRuleView struct {
	Base string `json:"base"`
	// Deny is evaluated across the union of ALL domain authorisations granted to the namespace,
	// and BEFORE allow. For a wildcard identifier `*.X`, deny rules are evaluated against both
	// `*.X` and `X`.
	Effect *string `json:"effect,omitempty"`
	// `subtree` DOES NOT MATCH ITS OWN BASE — authorising `api.example.com` itself requires an
	// `exact` rule. The base of a subtree is usually the higher-value name, and a grant intended
	// as "everything under X" must not silently include X.
	Kind string `json:"kind"`
	// Defaults to 1, hard maximum 3. Meaningful for `subtree` only.
	MaxLabelsBelow *int64 `json:"max_labels_below,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// DestinationPolicyView
type DestinationPolicyView struct {
	// A glob over Key Vault object names — a different, non-hostname namespace. Still not a regex.
	CertificateNameAllow []string `json:"certificate_name_allow,omitempty"`
	DestinationID        string   `json:"destination_id"`
	// A destination policy names EXACTLY ONE vault resource id. Subscription and resource-group
	// PREFIXES ARE FORBIDDEN: with a prefix, an attacker creates a vault matching it, the
	// capability probe returns `404` ("the grant works, the name is free"), and the probe CONFIRMS
	// the redirect rather than detecting it.
	KeyVaultID string `json:"key_vault_id"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// AllowedKeyPolicy -- EC must be REPRESENTABLE and is not PERMITTED in v1. Enabling it later is
// then a policy change, not a schema change.
type AllowedKeyPolicy struct {
	Algorithm string   `json:"algorithm"`
	Curves    []string `json:"curves,omitempty"`
	Sizes     []int64  `json:"sizes,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// ValidationBindingCollection
type ValidationBindingCollection struct {
	Items         []ValidationBinding `json:"items"`
	NextPageToken *string             `json:"next_page_token,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// ValidationBinding
type ValidationBinding struct {
	DelegationTargets     []string `json:"delegation_targets,omitempty"`
	Healthy               bool     `json:"healthy"`
	ID                    string   `json:"id"`
	LastCheckedAt         *string  `json:"last_checked_at,omitempty"`
	Mode                  string   `json:"mode"`
	PermittedNamePatterns []string `json:"permitted_name_patterns"`
	// When unhealthy, the EXACT record the customer must create. An unhealthy binding that does
	// not say what to create is a support ticket.
	RequiredCname    *string `json:"required_cname,omitempty"`
	WildcardsAllowed bool    `json:"wildcards_allowed"`
	ZoneID           *string `json:"zone_id,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// CertificateRegistration -- The public management representation. An EXPLICIT PROJECTION,
// never a serialisation of the catalogue document.
type CertificateRegistration struct {
	APIVersion        string              `json:"api_version"`
	Kind              string              `json:"kind"`
	Links             Links               `json:"links"`
	Name              string              `json:"name"`
	Namespace         string              `json:"namespace"`
	RegistrationID    string              `json:"registration_id"`
	ServiceInstanceID string              `json:"service_instance_id"`
	Spec              CertificateSpecRead `json:"spec"`
	Status            RegistrationStatus  `json:"status"`
	// Service-owned metadata. Separate from `labels` so guarantee G-6 holds: the service never
	// writes into the client's labels.
	SystemLabels map[string]string `json:"system_labels,omitempty"`
	// Non-fatal advice. On the FIRST resolution of `validation_binding: "auto"` the service MUST
	// include an entry naming the binding chosen and recommending an explicit value.
	Warnings []Warning `json:"warnings,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// CertificateSpecEnvelope -- The `PUT` request body is JUST THE SPEC. A body containing
// `status`, `system_labels`, `spec.revision`, `spec.generation` or `spec.hash` is rejected `400
// invalid_spec`. Read-only fields are NEVER silently ignored — silent ignoring is how a client
// comes to believe it set something it did not.
type CertificateSpecEnvelope struct {
	Spec CertificateSpecFields `json:"spec"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// CertificateSpecFields -- The fields common to the write and the read projection.
type CertificateSpecFields struct {
	// Required `true` for `deletion_policy: delete` against a purge-protected vault; otherwise
	// `400 acknowledgement_required`.
	AcknowledgeIrreversibleDelete *bool `json:"acknowledge_irreversible_delete,omitempty"`
	// A SENTINEL, not a materialised default. `default` is resolved at each issuance to the
	// service's current default. It prevents the "set `tlsserver` for a test, delete the line,
	// silently keep a 25-name cap and a 45-day lifetime" trap.
	ACMEProfile *string `json:"acme_profile,omitempty"`
	// RESERVED; DO NOT SET. Held for create-time adoption of a matching destination.
	AdoptExistingDestination *bool `json:"adopt_existing_destination,omitempty"`
	// RESERVED; DO NOT SET. Held for D-30, an explicit common name if the Key Vault CSR experiment
	// shows one is unavoidable. Deriving the common name from the "first" `dns_names` entry is
	// impossible: a Set has no first, and deriving it from canonical sort order means adding a
	// name silently changes the subject and forces a reissue for a reason no user could predict.
	CommonName *string `json:"common_name,omitempty"`
	// Optional, and hoisted to the TOP of `spec` rather than living inside `consumer_probe`,
	// because it also drives the `key.exportable` validator and the destination compatibility
	// checks, which are independent of whether a probe runs. OMISSION MEANS NO CONSUMER-SPECIFIC
	// VALIDATION — never a block. Validated against `capabilities.consumer_profiles`, not against
	// a client-side constant, so a consumer outside the v1 matrix is never blocked by a provider
	// release.
	ConsumerProfile *string         `json:"consumer_profile,omitempty"`
	DeletionPolicy  *DeletionPolicy `json:"deletion_policy,omitempty"`
	// RESERVED; DO NOT SET. Held for v2 multi-destination. Structurally impossible with Key
	// Vault-generated keys, because each vault holds a different key pair.
	Deliveries []map[string]json.RawMessage `json:"deliveries,omitempty"`
	// Stored byte-for-byte (guarantee G-6).
	Description *string            `json:"description,omitempty"`
	Destination *DestinationFields `json:"destination,omitempty"`
	DNSNames    []string           `json:"dns_names,omitempty"`
	Key         *KeyPolicyWrite    `json:"key,omitempty"`
	Labels      map[string]string  `json:"labels,omitempty"`
	// RESERVED; DO NOT SET. Held for v1.1, once an email transport exists anywhere in the
	// platform. Shipping the field without a transport would ship a lie.
	Notifications map[string]json.RawMessage `json:"notifications,omitempty"`
	Renewal       *RenewalSpec               `json:"renewal,omitempty"`
	// RESERVED; DO NOT SET. Held for v1.1 platform-approved duplicate identifier sets across
	// namespaces.
	SharedIdentifierSet *string `json:"shared_identifier_set,omitempty"`
	// A SENTINEL, not a materialised default. `auto` is resolved at each issuance and the resolved
	// value appears as `status.resolved_validation_binding`. This removes the `Optional +
	// Computed` "cannot be reverted" trap.
	ValidationBinding *string           `json:"validation_binding,omitempty"`
	Verification      *VerificationSpec `json:"verification,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// CertificateSpecRead -- The read projection adds the three counters. `spec.metadataRevision`
// (an internal bookkeeping counter) and `fulfilled_spec_revision` DO NOT EXIST ON THE WIRE.
type CertificateSpecRead struct {
	// Required `true` for `deletion_policy: delete` against a purge-protected vault; otherwise
	// `400 acknowledgement_required`.
	AcknowledgeIrreversibleDelete *bool `json:"acknowledge_irreversible_delete,omitempty"`
	// A SENTINEL, not a materialised default. `default` is resolved at each issuance to the
	// service's current default. It prevents the "set `tlsserver` for a test, delete the line,
	// silently keep a 25-name cap and a 45-day lifetime" trap.
	ACMEProfile *string `json:"acme_profile,omitempty"`
	// RESERVED; DO NOT SET. Held for create-time adoption of a matching destination.
	AdoptExistingDestination *bool `json:"adopt_existing_destination,omitempty"`
	// RESERVED; DO NOT SET. Held for D-30, an explicit common name if the Key Vault CSR experiment
	// shows one is unavoidable. Deriving the common name from the "first" `dns_names` entry is
	// impossible: a Set has no first, and deriving it from canonical sort order means adding a
	// name silently changes the subject and forces a reissue for a reason no user could predict.
	CommonName *string `json:"common_name,omitempty"`
	// Optional, and hoisted to the TOP of `spec` rather than living inside `consumer_probe`,
	// because it also drives the `key.exportable` validator and the destination compatibility
	// checks, which are independent of whether a probe runs. OMISSION MEANS NO CONSUMER-SPECIFIC
	// VALIDATION — never a block. Validated against `capabilities.consumer_profiles`, not against
	// a client-side constant, so a consumer outside the v1 matrix is never blocked by a provider
	// release.
	ConsumerProfile *string         `json:"consumer_profile,omitempty"`
	DeletionPolicy  *DeletionPolicy `json:"deletion_policy,omitempty"`
	// RESERVED; DO NOT SET. Held for v2 multi-destination. Structurally impossible with Key
	// Vault-generated keys, because each vault holds a different key pair.
	Deliveries []map[string]json.RawMessage `json:"deliveries,omitempty"`
	// Stored byte-for-byte (guarantee G-6).
	Description *string          `json:"description,omitempty"`
	Destination *DestinationRead `json:"destination,omitempty"`
	DNSNames    []string         `json:"dns_names,omitempty"`
	// Monotonic. Incremented ONLY when `hash` — the issuance hash — changes.
	// `status.observed_generation` is the generation whose certificate is actually published;
	// fulfilment is `observed_generation == generation && phase == "ready"`.
	Generation int64 `json:"generation"`
	// The issuance hash, computed SERVER-SIDE on every spec write over the canonical JSON of the
	// issuance-relevant fields. Never client-supplied.
	Hash   string            `json:"hash"`
	Key    *KeyPolicyWrite   `json:"key,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	// RESERVED; DO NOT SET. Held for v1.1, once an email transport exists anywhere in the
	// platform. Shipping the field without a transport would ship a lie.
	Notifications map[string]json.RawMessage `json:"notifications,omitempty"`
	Renewal       *RenewalSpec               `json:"renewal,omitempty"`
	// Monotonic. Incremented on ANY spec write, issuance-relevant or metadata-only. This is the
	// ETag source.
	Revision int64 `json:"revision"`
	// RESERVED; DO NOT SET. Held for v1.1 platform-approved duplicate identifier sets across
	// namespaces.
	SharedIdentifierSet *string `json:"shared_identifier_set,omitempty"`
	// A SENTINEL, not a materialised default. `auto` is resolved at each issuance and the resolved
	// value appears as `status.resolved_validation_binding`. This removes the `Optional +
	// Computed` "cannot be reverted" trap.
	ValidationBinding *string           `json:"validation_binding,omitempty"`
	Verification      *VerificationSpec `json:"verification,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// DestinationFields -- BOTH FIELDS EXIST IN THE WIRE CONTRACT FROM DAY ONE. In v1 the caller
// supplies `key_vault_id` and `certificate_name`, and the service resolves them against the
// namespace's destination policies. `destination_id` is required by POLICY, never by the
// schema, so making it mandatory later stays additive — making a Terraform attribute `Required`
// after publication would be breaking; requiring it server-side is not.
type DestinationFields struct {
	// The Key Vault certificate object name.
	CertificateName *string `json:"certificate_name,omitempty"`
	// Names a namespace destination policy. Optional in v1; when supplied it MUST match the
	// resolved policy or the request is rejected. It becomes REQUIRED when more than one
	// destination policy in the namespace could match the supplied `key_vault_id`, and its absence
	// is then `400 destination_ambiguous`. It is persisted alongside the resolved vault id, and
	// the destination is re-resolved FROM THE POLICY ID — not from the stored vault id — at every
	// renewal and immediately before every publish; otherwise removing a vault from a namespace's
	// grants stops new registrations but does not stop an existing one publishing into it every 45
	// days.
	DestinationID *string `json:"destination_id,omitempty"`
	KeyVaultID    *string `json:"key_vault_id,omitempty"`
	Type          *string `json:"type,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// DestinationRead
type DestinationRead struct {
	// The Key Vault certificate object name.
	CertificateName string `json:"certificate_name"`
	// `hex(sha256(lower(vaultResourceId) + "|" + lower(certificateName)))` over the NORMALISED
	// inputs. Computed over un-normalised inputs, `Payments-Prod/api` and `payments-prod/api` hash
	// differently and the ownership guard never fires.
	DestinationHash *string `json:"destination_hash,omitempty"`
	// Names a namespace destination policy. Optional in v1; when supplied it MUST match the
	// resolved policy or the request is rejected. It becomes REQUIRED when more than one
	// destination policy in the namespace could match the supplied `key_vault_id`, and its absence
	// is then `400 destination_ambiguous`. It is persisted alongside the resolved vault id, and
	// the destination is re-resolved FROM THE POLICY ID — not from the stored vault id — at every
	// renewal and immediately before every publish; otherwise removing a vault from a namespace's
	// grants stops new registrations but does not stop an existing one publishing into it every 45
	// days.
	DestinationID *string `json:"destination_id,omitempty"`
	KeyVaultID    string  `json:"key_vault_id"`
	Type          *string `json:"type,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// KeyPolicyWrite
type KeyPolicyWrite struct {
	// EC stays representable so enabling it is a service policy change rather than a contract
	// change, but `capabilities.key_policies` advertises RSA only in v1. `RSA-HSM`, `EC-HSM` and
	// Managed HSM destinations are rejected unconditionally: non-exportable keys are unusable by
	// every consumer in the v1 matrix.
	Algorithm *string `json:"algorithm,omitempty"`
	Curve     *string `json:"curve,omitempty"`
	// DEFAULTS TO TRUE, and `false` is rejected `400 destination_incompatible_with_consumer`
	// unless `consumer_profile` is `keyvault_crypto_only`. Every consumer in the v1 matrix reads
	// the PKCS#12 secret; without an exportable key the addressable secret contains no private
	// key. Take `false` and the apply succeeds, every status field is green, and the Application
	// Gateway listener will not start — surfacing hours later in a DIFFERENT Terraform
	// configuration as an Azure error. That is the worst failure class in the product.
	Exportable *bool  `json:"exportable,omitempty"`
	Size       *int64 `json:"size,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// RenewalSpec
type RenewalSpec struct {
	// RESERVED; DO NOT SET. Held for v1.1, a per-registration ARI-unavailable lead time. Service
	// policy; never a hard-coded day count.
	FallbackLeadTime *string `json:"fallback_lead_time,omitempty"`
	// Suspension is expressed here rather than as an action, so it is declarative, visible in
	// `terraform plan`, and survives Terraform-driven reconciliation. An action would be invisible
	// to Terraform and reverted by the next apply.
	Mode   *string `json:"mode,omitempty"`
	UseARI *bool   `json:"use_ari,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// VerificationSpec
type VerificationSpec struct {
	ConsumerProbe *ConsumerProbe `json:"consumer_probe,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// ConsumerProbe
type ConsumerProbe struct {
	// Defaults to FALSE, because reachability is constrained by the networking decision and a
	// probe that cannot connect produces a false `consumer_stale`.
	Enabled *bool `json:"enabled,omitempty"`
	// An ARRAY, because one certificate frequently fronts several listeners, and structured rather
	// than a flat `host:443` string, which requires parsing and cannot express SNI separately from
	// host.
	Endpoints      []ProbeEndpoint `json:"endpoints,omitempty"`
	ExpectedPickup *string         `json:"expected_pickup,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// ProbeEndpoint
type ProbeEndpoint struct {
	Host string  `json:"host"`
	Port *int64  `json:"port,omitempty"`
	SNI  *string `json:"sni,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// RegistrationStatus -- SERVICE-WRITTEN, CLIENT-READ. No client request can set any part of it.
type RegistrationStatus struct {
	Audit      *Audit                `json:"audit,omitempty"`
	Conditions []Condition           `json:"conditions,omitempty"`
	Consumers  []ConsumerObservation `json:"consumers,omitempty"`
	// `null` while the first issuance is in flight. An update publishes the new version, verifies
	// it, and only then flips this field: the working certificate is never removed before its
	// replacement is verified (guarantee G-7).
	CurrentCertificate *CurrentCertificate `json:"current_certificate,omitempty"`
	// `consumer_unverifiable` IS MANDATORY AND MUST BE SURFACED. Silence must never read as
	// success.
	DeliveryStage string `json:"delivery_stage"`
	// The registration's standing instruction. `authorization_revoked` means renewal
	// re-authorisation failed: renewal stops, the published certificate is RETAINED, and the
	// registration stays readable.
	LifecycleState     string            `json:"lifecycle_state"`
	ObservedGeneration int64             `json:"observed_generation"`
	Operation          *OperationSummary `json:"operation,omitempty"`
	Ownership          *Ownership        `json:"ownership,omitempty"`
	// Where the CURRENT GENERATION is in its lifecycle. `ready` means `observed_generation ==
	// spec.generation`.
	Phase               string               `json:"phase"`
	PreviousCertificate *PreviousCertificate `json:"previous_certificate,omitempty"`
	// One service-owned knob, exposed read-only. `merge` in v1.
	PublicationMode           *string        `json:"publication_mode,omitempty"`
	Renewal                   *RenewalStatus `json:"renewal,omitempty"`
	ResolvedACMEProfile       *string        `json:"resolved_acme_profile,omitempty"`
	ResolvedCertificateName   *string        `json:"resolved_certificate_name,omitempty"`
	ResolvedValidationBinding *string        `json:"resolved_validation_binding,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// CurrentCertificate -- URIs ONLY. The service returns no certificate material here. For a Key
// Vault CERTIFICATE the sibling SECRET object's value is the PKCS#12 bundle including the
// private key; publishing `versionless_secret_id` is safe because it is a URI and reading it
// requires Key Vault RBAC the Terraform principal need not hold.
type CurrentCertificate struct {
	ACMEProfile              *string                    `json:"acme_profile,omitempty"`
	DNSNames                 []string                   `json:"dns_names,omitempty"`
	IssuedAt                 *string                    `json:"issued_at,omitempty"`
	Issuer                   *string                    `json:"issuer,omitempty"`
	Key                      map[string]json.RawMessage `json:"key,omitempty"`
	NotAfter                 string                     `json:"not_after"`
	NotBefore                string                     `json:"not_before"`
	PublishedAt              *string                    `json:"published_at,omitempty"`
	SerialNumber             *string                    `json:"serial_number,omitempty"`
	ThumbprintSHA256         string                     `json:"thumbprint_sha256"`
	VersionCertificateID     *string                    `json:"version_certificate_id,omitempty"`
	VersionSecretID          *string                    `json:"version_secret_id,omitempty"`
	VersionlessCertificateID *string                    `json:"versionless_certificate_id,omitempty"`
	VersionlessSecretID      *string                    `json:"versionless_secret_id,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// PreviousCertificate
type PreviousCertificate struct {
	NotAfter         *string `json:"not_after,omitempty"`
	ThumbprintSHA256 *string `json:"thumbprint_sha256,omitempty"`
	VersionSecretID  *string `json:"version_secret_id,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// ConsumerObservation
type ConsumerObservation struct {
	Host                     string  `json:"host"`
	LastCheckedAt            *string `json:"last_checked_at,omitempty"`
	ObservedThumbprintSHA256 *string `json:"observed_thumbprint_sha256,omitempty"`
	Port                     *int64  `json:"port,omitempty"`
	State                    string  `json:"state"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// RenewalStatus
type RenewalStatus struct {
	ARIWindowEnd            *string `json:"ari_window_end,omitempty"`
	ARIWindowStart          *string `json:"ari_window_start,omitempty"`
	ConsecutiveFailures     *int64  `json:"consecutive_failures,omitempty"`
	LastSuccessfulRenewalAt *string `json:"last_successful_renewal_at,omitempty"`
	NextAttemptAt           *string `json:"next_attempt_at,omitempty"`
	NextCheckAt             *string `json:"next_check_at,omitempty"`
	// `ari` when the CA's renewal information drove the window; `fallback` when it was unavailable
	// and the service used its configured lead time.
	Source *string `json:"source,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// OperationSummary
type OperationSummary struct {
	Attempt   *int64                     `json:"attempt,omitempty"`
	ID        *string                    `json:"id,omitempty"`
	LastError *OperationError            `json:"last_error,omitempty"`
	Phase     *OperationPhase            `json:"phase,omitempty"`
	StartedAt *string                    `json:"started_at,omitempty"`
	State     RegistrationOperationState `json:"state"`
	Type      *OperationType             `json:"type,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// Ownership
type Ownership struct {
	AdoptedExisting  *bool   `json:"adopted_existing,omitempty"`
	ClaimedAt        *string `json:"claimed_at,omitempty"`
	DestinationClaim *string `json:"destination_claim,omitempty"`
	// A LABEL ONLY. Never an evaluation input.
	OwnerDisplayName   *string `json:"owner_display_name,omitempty"`
	OwnerPrincipalID   *string `json:"owner_principal_id,omitempty"`
	OwnerPrincipalType *string `json:"owner_principal_type,omitempty"`
	Transferable       *bool   `json:"transferable,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// Condition
type Condition struct {
	LastTransitionAt *string `json:"last_transition_at,omitempty"`
	Message          *string `json:"message,omitempty"`
	PolicyRevision   *int64  `json:"policy_revision,omitempty"`
	Reason           *string `json:"reason,omitempty"`
	Status           string  `json:"status"`
	// At minimum `Authorized`, carrying the `policy_revision` that last authorised the
	// registration. Unknown types are rendered verbatim.
	Type string `json:"type"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// Audit
type Audit struct {
	CreatedAt *string `json:"created_at,omitempty"`
	CreatedBy *string `json:"created_by,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	UpdatedBy *string `json:"updated_by,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// RegistrationCollection
type RegistrationCollection struct {
	Items []RegistrationSummary `json:"items"`
	// Opaque and service-signed. Absent or `null` on the last page. Never leaks the existence of
	// unreadable registrations, because authorisation filtering runs before pagination.
	NextPageToken *string `json:"next_page_token,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// RegistrationSummary
type RegistrationSummary struct {
	Links          Links                      `json:"links"`
	Name           string                     `json:"name"`
	Namespace      string                     `json:"namespace"`
	RegistrationID string                     `json:"registration_id"`
	Spec           map[string]json.RawMessage `json:"spec"`
	// The volatile status lives on the COLLECTION view, not on the resource: a probe running every
	// 30 minutes can flip `delivery_stage` between two plans minutes apart, and a drift note on
	// every plan teaches teams to ignore drift notes.
	Status map[string]json.RawMessage `json:"status"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// Operation
type Operation struct {
	Attempt     *int64  `json:"attempt,omitempty"`
	CompletedAt *string `json:"completed_at,omitempty"`
	CreatedAt   string  `json:"created_at"`
	// A taxonomy code, normally `acme_rate_limited`, `validation_budget_exhausted` or
	// `rekey_awaiting_consumer_observation`.
	DeferralReason *string         `json:"deferral_reason,omitempty"`
	Error          *OperationError `json:"error,omitempty"`
	// Populated by the admission gate. The gate can defer work by DAYS, not minutes, and no client
	// timeout value accommodates that — so the client fails fast at apply time with a message
	// naming the reset time instead of waiting out its timeout in silence.
	EstimatedStart   *string                    `json:"estimated_start,omitempty"`
	ID               string                     `json:"id"`
	Phase            *OperationPhase            `json:"phase,omitempty"`
	Registration     map[string]json.RawMessage `json:"registration"`
	Result           map[string]json.RawMessage `json:"result,omitempty"`
	RetryAfter       *string                    `json:"retry_after,omitempty"`
	State            OperationState             `json:"state"`
	TargetGeneration int64                      `json:"target_generation"`
	Type             OperationType              `json:"type"`
	UpdatedAt        string                     `json:"updated_at"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// OperationError
type OperationError struct {
	// A code from `contracts/errors/error-codes.yaml` whose surface is `op` or `both`.
	Code string `json:"code"`
	// Sanitised. Never an exception's `str()`, never an ACME order or challenge URL.
	Message    string  `json:"message"`
	OccurredAt *string `json:"occurred_at,omitempty"`
	Retryable  bool    `json:"retryable"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// OperationAccepted
type OperationAccepted struct {
	EstimatedStart *string                  `json:"estimated_start,omitempty"`
	OperationID    string                   `json:"operation_id"`
	Registration   *CertificateRegistration `json:"registration,omitempty"`
	RegistrationID string                   `json:"registration_id"`
	Status         string                   `json:"status"`
	// MANDATORY on every `202`. It is what the operation-expiry fallback compares against when the
	// operation record has aged out.
	TargetGeneration int64 `json:"target_generation"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// CancelRequest
type CancelRequest struct {
	Reason string `json:"reason"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// RekeyRequest
type RekeyRequest struct {
	// MANDATORY. Anything else is `400 invalid_rekey_reason`.
	Reason string `json:"reason"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// ClaimRequest
type ClaimRequest struct {
	// Ownership transfer is never implicit.
	AcknowledgeTransfer bool `json:"acknowledge_transfer"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// RevokeRequest
type RevokeRequest struct {
	// An RFC 5280 CRL reason code. Required.
	ReasonCode int64 `json:"reason_code"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// AdoptCertificateRequest
type AdoptCertificateRequest struct {
	// Adoption is observe-only in v1.
	AcknowledgeObserveOnly   *bool   `json:"acknowledge_observe_only,omitempty"`
	ExpectedThumbprintSHA256 *string `json:"expected_thumbprint_sha256,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// RecoverDestinationRequest
type RecoverDestinationRequest struct {
	ConfirmDestination map[string]json.RawMessage `json:"confirm_destination"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// AdoptOwnershipRequest
type AdoptOwnershipRequest struct {
	AcknowledgeOrphan   bool   `json:"acknowledge_orphan"`
	OwnerRegistrationID string `json:"owner_registration_id"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// AcceptRestoreRequest
type AcceptRestoreRequest struct {
	AcknowledgeRestoreVerified bool  `json:"acknowledge_restore_verified"`
	ExpectedEpoch              int64 `json:"expected_epoch"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// AcceptRestoreResult
type AcceptRestoreResult struct {
	ClearedAt string  `json:"cleared_at"`
	ClearedBy *string `json:"cleared_by,omitempty"`
	Epoch     int64   `json:"epoch"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// DestinationOwnershipView
type DestinationOwnershipView struct {
	CertificateName     *string `json:"certificate_name,omitempty"`
	ClaimedAt           *string `json:"claimed_at,omitempty"`
	DestinationHash     string  `json:"destination_hash"`
	KeyVaultID          *string `json:"key_vault_id,omitempty"`
	OwnerName           *string `json:"owner_name,omitempty"`
	OwnerNamespace      *string `json:"owner_namespace,omitempty"`
	OwnerRegistrationID *string `json:"owner_registration_id,omitempty"`
	ServiceInstanceID   *string `json:"service_instance_id,omitempty"`
	State               string  `json:"state"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// ExposureCollection
type ExposureCollection struct {
	// Always `true`. A partial exposure answer is NEVER returned: incompleteness is `503
	// exposure_inventory_incomplete`, because a silently partial answer is worse than no answer,
	// since it is acted on.
	Complete      bool          `json:"complete"`
	Items         []ExposureRow `json:"items"`
	NextPageToken *string       `json:"next_page_token,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// ExposureRow -- NO certificate material, NO secret value, NO PKCS#12 bundle, and no thumbprint
// of anything unpublished.
type ExposureRow struct {
	AssignmentType string                     `json:"assignment_type"`
	Current        map[string]json.RawMessage `json:"current,omitempty"`
	DeliveryStage  *string                    `json:"delivery_stage,omitempty"`
	Destination    map[string]json.RawMessage `json:"destination"`
	Name           string                     `json:"name"`
	Namespace      string                     `json:"namespace"`
	// The assignments that grant the read.
	Roles []string `json:"roles"`
	// Vault or object scope.
	Scope string `json:"scope"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// RetainedCollection
type RetainedCollection struct {
	Items         []RetainedRow `json:"items"`
	NextPageToken *string       `json:"next_page_token,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}

// RetainedRow -- Exists so expiry alerting for a retained certificate is routed to the
// decommissioning actor, not to the platform on-call, and is suppressed once `not_after`
// passes.
type RetainedRow struct {
	Destination      map[string]json.RawMessage `json:"destination"`
	Name             string                     `json:"name"`
	Namespace        string                     `json:"namespace"`
	NotAfter         *string                    `json:"not_after,omitempty"`
	RegistrationID   *string                    `json:"registration_id,omitempty"`
	RetainedAt       string                     `json:"retained_at"`
	RetainedBy       string                     `json:"retained_by"`
	RetainedUntil    *string                    `json:"retained_until,omitempty"`
	ThumbprintSHA256 *string                    `json:"thumbprint_sha256,omitempty"`
	// Extra preserves fields this build does not know about, so a newer
	// writer's field survives an older reader's round trip.
	Extra map[string]json.RawMessage `json:"-"`
}
