// Code generated by contracts/tools/generate.py v1.0.0 from contracts/primitives/primitives.yaml; DO NOT EDIT.
//
// Edit contracts/primitives/primitives.yaml and run `make contracts-generate`. Hand edits are reverted by the
// drift check in `make contracts-verify`.

package contracts

import (
	"regexp"
	"testing"
)

// patternSelfTestCase pairs an EMITTED constant with the corpus it must answer to. The
// pattern field reads the constant itself, never a copy of its text: a copy would pass
// while the constant the rest of the build uses was broken.
type patternSelfTestCase struct {
	name            string
	pattern         string
	examples        []string
	counterExamples []string
}

var patternSelfTests = []patternSelfTestCase{
	{
		name:    "NamespacePattern",
		pattern: NamespacePattern,
		examples: []string{
			"payments-prod",
			"a",
			"api",
			"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
		},
		counterExamples: []string{
			"",
			"-leading-hyphen",
			"trailing-hyphen-",
			"UPPERCASE",
			"pay_ments",
			"payments.prod",
			"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
		},
	},
	{
		name:    "TimestampPattern",
		pattern: TimestampPattern,
		examples: []string{
			"2026-11-28T04:11:01Z",
			"2026-01-01T00:00:00Z",
			"2026-12-31T23:59:59Z",
		},
		counterExamples: []string{
			"2026-11-28T04:11:01.238471Z",
			"2026-11-28T04:11:01+00:00",
			"2026-11-28 04:11:01Z",
			"2026-13-01T00:00:00Z",
			"2026-11-28T24:00:00Z",
		},
	},
	{
		name:    "HexPattern",
		pattern: HexPattern,
		examples: []string{
			"b210ac9e",
			"0",
			"deadbeef",
		},
		counterExamples: []string{
			"",
			"B2:10:AC",
			"DEADBEEF",
			"0x1f",
		},
	},
	{
		name:    "SHA256HexPattern",
		pattern: SHA256HexPattern,
		examples: []string{
			"3f786850e387550fdab836ed7e6dc881de23001b3f786850e387550fdab836ed",
		},
		counterExamples: []string{
			"3f786850e387550fdab836ed7e6dc881de23001b3f786850e387550fdab836e",
			"3f786850e387550fdab836ed7e6dc881de23001b3f786850e387550fdab836ed0",
			"3F786850E387550FDAB836ED7E6DC881DE23001B3F786850E387550FDAB836ED",
		},
	},
	{
		name:    "PrefixedSHA256Pattern",
		pattern: PrefixedSHA256Pattern,
		examples: []string{
			"sha256:3f786850e387550fdab836ed7e6dc881de23001b3f786850e387550fdab836ed",
		},
		counterExamples: []string{
			"3f786850e387550fdab836ed7e6dc881de23001b3f786850e387550fdab836ed",
			"sha512:3f786850e387550fdab836ed7e6dc881de23001b3f786850e387550fdab836ed",
		},
	},
	{
		name:    "ULIDPattern",
		pattern: ULIDPattern,
		examples: []string{
			"01J9K3P2XQ7R4S8TVWXYZ01234",
		},
		counterExamples: []string{
			"01J9K3P2XQ7R4S8TVWXYZ0123",
			"01j9k3p2xq7r4s8tvwxyz01234",
			"01J9K3P2XQ7R4S8TVWXYZ0123I",
		},
	},
	{
		name:    "OperationIDPattern",
		pattern: OperationIDPattern,
		examples: []string{
			"op_01J9K3P2XQ7R4S8TVWXYZ01234",
		},
		counterExamples: []string{
			"01J9K3P2XQ7R4S8TVWXYZ01234",
			"OP_01J9K3P2XQ7R4S8TVWXYZ01234",
			"op_01J9K3P2XQ7R4S8TVWXYZ0123",
		},
	},
	{
		name:    "GoDurationPattern",
		pattern: GoDurationPattern,
		examples: []string{
			"720h",
			"8h",
			"2m",
			"1h30m",
		},
		counterExamples: []string{
			"",
			"P30D",
			"30",
			"h",
			"-5m",
		},
	},
	{
		name:    "KeyVaultResourceIDPattern",
		pattern: KeyVaultResourceIDPattern,
		examples: []string{
			"/subscriptions/8a1c0b6e-3f2d-4b7a-9d5e-1c2b3a4d5e6f/resourceGroups/rg-payments-prod/providers/Microsoft.KeyVault/vaults/kv-payments-prod",
			"/subscriptions/8a1c0b6e-3f2d-4b7a-9d5e-1c2b3a4d5e6f/resourceGroups/RG1/providers/Microsoft.KeyVault/vaults/kv1",
		},
		counterExamples: []string{
			"/subscriptions/8a1c0b6e-3f2d-4b7a-9d5e-1c2b3a4d5e6f/resourceGroups/rg-payments-prod/providers/Microsoft-KeyVault/vaults/kv-payments-prod",
			"/subscriptions/short/resourceGroups/rg-payments-prod/providers/Microsoft.KeyVault/vaults/kv-payments-prod",
			"/subscriptions/8a1c0b6e-3f2d-4b7a-9d5e-1c2b3a4d5e6f/resourceGroups/rg-payments-prod/providers/Microsoft.KeyVault/vaults/kv",
			"/subscriptions/8a1c0b6e-3f2d-4b7a-9d5e-1c2b3a4d5e6f/resourceGroups/rg-payments-prod/providers/Microsoft.KeyVault/vaults/kv_payments",
			"/subscriptions/8a1c0b6e-3f2d-4b7a-9d5e-1c2b3a4d5e6f/resourceGroups/rg-payments-prod/providers/Microsoft.KeyVault/secrets/kv-payments-prod",
		},
	},
}

// TestGeneratedPatternsMatchTheirOwnExamples is the check the drift check cannot perform.
// Regenerating and comparing bytes proves the output matches the generator; it does not prove
// the output is USABLE. A regex constant that compiles and never matches is byte-identical to
// itself on every run, and every validation built on it is silently permissive.
//
// The corpus is authored once, in contracts/primitives/primitives.yaml, and generated into a
// test in BOTH consumers, so a pattern that regresses in one language fails there alone.
func TestGeneratedPatternsMatchTheirOwnExamples(t *testing.T) {
	for _, test := range patternSelfTests {
		t.Run(test.name, func(t *testing.T) {
			compiled, err := regexp.Compile(test.pattern)
			if err != nil {
				t.Fatalf("%s does not compile: %v", test.name, err)
			}
			for _, example := range test.examples {
				if !compiled.MatchString(example) {
					t.Errorf("%s does not match %q, which contracts/primitives/primitives.yaml "+
						"gives as one of its own examples. The constant compiles, so nothing else "+
						"notices: a pattern that never matches makes every validation built on it "+
						"silently permissive.", test.name, example)
				}
			}
			for _, counter := range test.counterExamples {
				if compiled.MatchString(counter) {
					t.Errorf("%s matches %q, which contracts/primitives/primitives.yaml gives "+
						"as one of its own counter-examples. A pattern that accepts what it is "+
						"meant to reject is an admission control that admits everything.",
						test.name, counter)
				}
			}
		})
	}
}
