// Code generated by contracts/tools/generate.py v1.0.0 from contracts/primitives/primitives.yaml; DO NOT EDIT.
//
// Edit contracts/primitives/primitives.yaml and run `make contracts-generate`. Hand edits are reverted by the
// drift check in `make contracts-verify`.

package contracts

// THE ONE namespace and certificate-name grammar. No other module in this module may
// define a second one; a CI grep enforces the absence. Note the OPTIONAL group: the
// variant without it rejects a one-character namespace that this form accepts, and Go
// and Python would then validate differently.
const NamespacePattern = `^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$`

const NamespaceMinLength = 1
const NamespaceMaxLength = 63

// ReservedNamespaceNames satisfy the grammar and are rejected anyway.
var ReservedNamespaceNames = []string{
	"admin",
	"system",
	"platform",
	"policy",
	"internal",
}

// ReservedNamespacePrefixes are rejected wherever they appear at the start.
var ReservedNamespacePrefixes = []string{
	"_",
}

// The UTS-46 profile, PINNED. Transitional and non-transitional disagree on the four
// deviation characters, and golang.org/x/net/idna and Python's idna default
// differently. An unpinned mode is exactly the two implementations of
// "IDNA-2008 to A-label" that produced the deny-rule bypass.
const (
	UTS46TransitionalProcessing = false
	UTS46UseSTD3ASCIIRules      = true
	UTS46CheckHyphens           = true
	UTS46CheckBidi              = true
	UTS46CheckJoiners           = true
	UTS46VerifyDNSLength        = true
)

// NormalisationOrder is the normative substep order. IT IS NOT COMMUTATIVE: NFC (N5),
// then UTS-46 ToASCII (N6), then ASCII-lowercase the ASCII result (N7). Lowercasing
// BEFORE ToASCII applies a locale-sensitive or Unicode-aware casing rule to characters
// ToASCII would have mapped differently -- U+0130 and the Turkish dotless I being the
// worked examples -- and is a documented authorisation bypass. After ToASCII every
// octet is ASCII, so N7 is a byte operation and is locale-independent.
//
// The function itself is HAND-WRITTEN against contracts/primitives/vectors/. Only this
// table is generated.
var NormalisationOrder = []string{
	"N1: Reject empty input, input longer than 255 octets before processing, NUL, any C0 or C1 control character, any Unicode whitespace, \"%\", or any percent-encoded byte sequence.",
	"N2: Reject U+3002, U+FF0E or U+FF61 ANYWHERE. Runs before any split on \".\", so no implementation's splitting behaviour can matter.",
	"N3: Strip exactly one trailing \".\"; reject two or more trailing dots; reject a leading \".\"; reject any empty label.",
	"N4: If the string begins \"*.\", set wildcard=true and remove the marker. Reject \"*\" anywhere else, a bare \"*\", \"**\", and a \"*\" label that is not the entire first label.",
	"N5: Unicode-normalise the remainder to NFC.",
	"N6: Apply UTS-46 ToASCII with the pinned flags below.",
	"N7: ASCII-lowercase the result. AFTER ToASCII, never before. Byte operation only; never a locale-sensitive lowercase.",
	"N8: Reject any label that is empty, longer than 63 octets, begins or ends with \"-\", or contains any character outside [a-z0-9-].",
	"N9: Reject any label beginning \"xn--\" that does not decode as valid punycode, or whose decoded form does not re-encode to the identical label.",
	"N10: Reject a total length greater than 253 octets, excluding the implicit root label.",
	"N11: Reject fewer than two labels; reject an all-numeric rightmost label; reject an IPv4 or IPv6 literal in any form.",
	"N12: If wildcard, re-attach the \"*.\" prefix. The canonical form is exactly \"*.\" + base.",
	"N13: Emit the canonical form. This is the value stored, hashed, indexed, compared and logged.",
}

// DestinationHashExpression is the ONE construction. Computed over un-normalised
// inputs, Payments-Prod/api and payments-prod/api hash differently, the ownership
// guard never fires, and the second registration silently claims a destination the
// first owns.
const DestinationHashExpression = "hex(sha256(lower(vaultResourceId) + \"|\" + lower(certificateName)))"
const DestinationHashSeparator = "|"

// The pinned Public Suffix List snapshot. EXACTLY ONE copy exists in the repository;
// the policy validator, the rate-limit ledger and the registered-domain partition key
// all read it. Two snapshots means a policy that permits a wildcard and a ledger that
// counts it can disagree about what the registered domain is.
const PublicSuffixListSHA256 = "4b673689999dbaca60b93fa3e1da5752505ef9717b1c4dc44acbfdafd35679ea"
const PublicSuffixListSource = "https://publicsuffix.org/list/public_suffix_list.dat"

// Wire formats. RFC 3339, UTC, Z, SECOND precision, NO fractional seconds; lowercase
// hex with no separators. Leaving serialisation to each language's defaults makes every
// variant a state change and a drift note on an otherwise idle registration.
const (
	TimestampLayout           = "2006-01-02T15:04:05Z"
	TimestampPattern          = `^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):[0-5]\d:[0-5]\dZ$`
	HexPattern                = `^[0-9a-f]+$`
	SHA256HexPattern          = `^[0-9a-f]{64}$`
	PrefixedSHA256Pattern     = `^sha256:[0-9a-f]{64}$`
	ULIDPattern               = `^[0-9A-HJKMNP-TV-Z]{26}$`
	OperationIDPattern        = `^op_[0-9A-HJKMNP-TV-Z]{26}$`
	GoDurationPattern         = `^[0-9]+(ns|us|ms|s|m|h)([0-9]+(ns|us|ms|s|m|h))*$`
	KeyVaultResourceIDPattern = `^/subscriptions/[0-9a-fA-F-]{36}/resourceGroups/[^/]+/providers/Microsoft\.KeyVault/vaults/[A-Za-z0-9-]{3,24}$`
)

// ARM resource ids are stored and returned VERBATIM. The service must not normalise
// their casing; the client absorbs casing differences with a semantic-equality type.
const NormaliseARMResourceIDCasing = false
