// Code generated by contracts/tools/generate.py v1.0.0 from contracts/api/openapi.yaml; DO NOT EDIT.
//
// Edit contracts/api/openapi.yaml and run `make contracts-generate`. Hand edits are reverted by the
// drift check in `make contracts-verify`.

package fakeservice

import (
	"strconv"
	"strings"
)

// OperationID is an `operationId` declared by contracts/api/openapi.yaml.
//
// The fake dispatches on these constants rather than on path literals, so an operation withdrawn
// or renamed in the contract stops the fake COMPILING rather than leaving it answering at an
// address the service no longer serves.
type OperationID string

// The operations the contract declares, in document order.
const (
	// Unauthenticated liveness.
	OpGetHealth OperationID = "getHealth"
	// Service and caller identity, version, features and limits.
	OpGetCapabilities OperationID = "getCapabilities"
	// Namespaces visible to the caller.
	OpListNamespaces OperationID = "listNamespaces"
	// The namespace policy the caller is entitled to see.
	OpGetNamespace OperationID = "getNamespace"
	// Every validation binding visible to the caller, with health.
	OpListValidationBindings OperationID = "listValidationBindings"
	// One validation binding.
	OpGetValidationBinding OperationID = "getValidationBinding"
	// The paginated registration collection.
	OpListCertificates OperationID = "listCertificates"
	// The public management representation of one registration.
	OpGetCertificate OperationID = "getCertificate"
	// Create or update the desired specification.
	OpPutCertificate OperationID = "putCertificate"
	// Begin decommissioning.
	OpDeleteCertificate OperationID = "deleteCertificate"
	// Operation progress and result.
	OpGetOperation OperationID = "getOperation"
	// Authorised retry of the most recent failed operation.
	OpRetryCertificate OperationID = "retryCertificate"
	// Cancel a non-terminal operation.
	OpCancelCertificateOperation OperationID = "cancelCertificateOperation"
	// Issue a new certificate for the unchanged current specification.
	OpReissueCertificate OperationID = "reissueCertificate"
	// Rotate the private key in place — the production key-compromise response.
	OpRekeyCertificate OperationID = "rekeyCertificate"
	// Explicit ownership transfer.
	OpClaimCertificate OperationID = "claimCertificate"
	// Non-production test hook.
	OpForceRenewCertificate OperationID = "forceRenewCertificate"
	// Explicit revocation. Requires `Certificates.Revoke` and a reason code.
	OpRevokeCertificate OperationID = "revokeCertificate"
	// Observe-only adoption of an existing Key Vault CERTIFICATE.
	OpAdoptCertificate OperationID = "adoptCertificate"
	// Recover a soft-deleted destination certificate, then reissue.
	OpRecoverDestination OperationID = "recoverDestination"
	// Which registrations and destinations a principal could READ.
	OpGetExposure OperationID = "getExposure"
	// Adopt an orphaned ownership RECORD.
	OpAdoptOwnership OperationID = "adoptOwnership"
	// Retained (`retained-hold`) certificates and their expiry.
	OpListRetained OperationID = "listRetained"
	// Force a reconciliation sweep.
	OpForceReconcile OperationID = "forceReconcile"
	// Run a catalogue schema migration.
	OpRunMigration OperationID = "runMigration"
	// Rebuild the secondary due index.
	OpRebuildDueIndex OperationID = "rebuildDueIndex"
	// Clear the epoch fence after a verified restore.
	OpAcceptRestore OperationID = "acceptRestore"
	// Purge one challenge TXT value attributed to a decommissioned sibling instance.
	OpPurgeForeignChallengeValue OperationID = "purgeForeignChallengeValue"
)

// RouteSegment is one segment of a route's path. Exactly one field is set: Literal for fixed
// text, Param for a `{template}` variable whose value is captured on a match.
type RouteSegment struct {
	Literal string
	Param   string
}

// Route is one method-and-path pair the contract declares.
type Route struct {
	// OperationID is the contract's `operationId` for this method and path.
	OperationID OperationID
	// Method is the upper-case HTTP method.
	Method string
	// Path is the FULL path a client dials, server prefix included -- not the template relative
	// to the document's server. `/healthz` sits at the root because its operation overrides that
	// server; everything else is inside the `/v1` compatibility boundary.
	Path string
	// Segments is Path, split for matching.
	Segments []RouteSegment
	// Statuses are the response keys the contract declares, spelled exactly as the document
	// spells them -- wildcard ranges such as "5XX" included.
	Statuses []string
	// PreconditionHeaders are the conditional-request headers the operation accepts.
	PreconditionHeaders []string
	// RequiresPrecondition is true when the contract declares `428` for this operation AND
	// accepts both If-None-Match and If-Match. That is the rule which makes a lost update
	// structurally impossible, and which must fail the PROVIDER's own suite when it is forgotten.
	RequiresPrecondition bool
}

// Routes is every operation the contract declares, in document order.
var Routes = []Route{
	{
		OperationID: OpGetHealth,
		Method:      "GET",
		Path:        "/healthz",
		Segments:    []RouteSegment{{Literal: "healthz"}},
		Statuses:    []string{"200"},
	},
	{
		OperationID: OpGetCapabilities,
		Method:      "GET",
		Path:        "/v1/capabilities",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "capabilities"}},
		Statuses:    []string{"200", "401", "406", "503"},
	},
	{
		OperationID: OpListNamespaces,
		Method:      "GET",
		Path:        "/v1/namespaces",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}},
		Statuses:    []string{"200", "401", "403", "406", "429", "5XX"},
	},
	{
		OperationID: OpGetNamespace,
		Method:      "GET",
		Path:        "/v1/namespaces/{namespace}",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}},
		Statuses:    []string{"200", "401", "403", "406", "429", "5XX"},
	},
	{
		OperationID: OpListValidationBindings,
		Method:      "GET",
		Path:        "/v1/validation-bindings",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "validation-bindings"}},
		Statuses:    []string{"200", "401", "403", "406", "429", "5XX"},
	},
	{
		OperationID: OpGetValidationBinding,
		Method:      "GET",
		Path:        "/v1/validation-bindings/{bindingId}",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "validation-bindings"}, {Param: "bindingId"}},
		Statuses:    []string{"200", "401", "403", "404", "406", "429", "5XX"},
	},
	{
		OperationID: OpListCertificates,
		Method:      "GET",
		Path:        "/v1/namespaces/{namespace}/certificates",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}, {Literal: "certificates"}},
		Statuses:    []string{"200", "400", "401", "403", "406", "429", "5XX"},
	},
	{
		OperationID: OpGetCertificate,
		Method:      "GET",
		Path:        "/v1/namespaces/{namespace}/certificates/{name}",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}, {Literal: "certificates"}, {Param: "name"}},
		Statuses:    []string{"200", "401", "403", "404", "406", "410", "429", "5XX"},
	},
	{
		OperationID:          OpPutCertificate,
		Method:               "PUT",
		Path:                 "/v1/namespaces/{namespace}/certificates/{name}",
		Segments:             []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}, {Literal: "certificates"}, {Param: "name"}},
		Statuses:             []string{"200", "201", "202", "400", "401", "403", "406", "409", "412", "422", "428", "429", "5XX"},
		PreconditionHeaders:  []string{"If-None-Match", "If-Match"},
		RequiresPrecondition: true,
	},
	{
		OperationID:         OpDeleteCertificate,
		Method:              "DELETE",
		Path:                "/v1/namespaces/{namespace}/certificates/{name}",
		Segments:            []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}, {Literal: "certificates"}, {Param: "name"}},
		Statuses:            []string{"202", "204", "400", "401", "403", "404", "406", "409", "410", "412", "429", "5XX"},
		PreconditionHeaders: []string{"If-Match"},
	},
	{
		OperationID: OpGetOperation,
		Method:      "GET",
		Path:        "/v1/operations/{operationId}",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "operations"}, {Param: "operationId"}},
		Statuses:    []string{"200", "401", "403", "404", "406", "410", "429", "5XX"},
	},
	{
		OperationID: OpRetryCertificate,
		Method:      "POST",
		Path:        "/v1/namespaces/{namespace}/certificates/{name}/actions/retry",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}, {Literal: "certificates"}, {Param: "name"}, {Literal: "actions"}, {Literal: "retry"}},
		Statuses:    []string{"202", "400", "401", "403", "404", "406", "409", "410", "429", "5XX"},
	},
	{
		OperationID: OpCancelCertificateOperation,
		Method:      "POST",
		Path:        "/v1/namespaces/{namespace}/certificates/{name}/actions/cancel",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}, {Literal: "certificates"}, {Param: "name"}, {Literal: "actions"}, {Literal: "cancel"}},
		Statuses:    []string{"202", "400", "401", "403", "404", "406", "409", "410", "429", "5XX"},
	},
	{
		OperationID: OpReissueCertificate,
		Method:      "POST",
		Path:        "/v1/namespaces/{namespace}/certificates/{name}/actions/reissue",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}, {Literal: "certificates"}, {Param: "name"}, {Literal: "actions"}, {Literal: "reissue"}},
		Statuses:    []string{"202", "400", "401", "403", "404", "406", "409", "410", "429", "5XX"},
	},
	{
		OperationID: OpRekeyCertificate,
		Method:      "POST",
		Path:        "/v1/namespaces/{namespace}/certificates/{name}/actions/rekey",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}, {Literal: "certificates"}, {Param: "name"}, {Literal: "actions"}, {Literal: "rekey"}},
		Statuses:    []string{"202", "400", "401", "403", "404", "406", "409", "410", "429", "5XX"},
	},
	{
		OperationID: OpClaimCertificate,
		Method:      "POST",
		Path:        "/v1/namespaces/{namespace}/certificates/{name}/actions/claim",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}, {Literal: "certificates"}, {Param: "name"}, {Literal: "actions"}, {Literal: "claim"}},
		Statuses:    []string{"200", "400", "401", "403", "404", "406", "409", "410", "429", "5XX"},
	},
	{
		OperationID: OpForceRenewCertificate,
		Method:      "POST",
		Path:        "/v1/namespaces/{namespace}/certificates/{name}/actions/force-renew",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}, {Literal: "certificates"}, {Param: "name"}, {Literal: "actions"}, {Literal: "force-renew"}},
		Statuses:    []string{"202", "400", "401", "403", "404", "406", "409", "410", "429", "5XX"},
	},
	{
		OperationID: OpRevokeCertificate,
		Method:      "POST",
		Path:        "/v1/namespaces/{namespace}/certificates/{name}/actions/revoke",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}, {Literal: "certificates"}, {Param: "name"}, {Literal: "actions"}, {Literal: "revoke"}},
		Statuses:    []string{"202", "400", "401", "403", "404", "406", "409", "410", "429", "5XX"},
	},
	{
		OperationID: OpAdoptCertificate,
		Method:      "POST",
		Path:        "/v1/namespaces/{namespace}/certificates/{name}/actions/adopt-certificate",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}, {Literal: "certificates"}, {Param: "name"}, {Literal: "actions"}, {Literal: "adopt-certificate"}},
		Statuses:    []string{"202", "400", "401", "403", "404", "406", "409", "410", "429", "5XX"},
	},
	{
		OperationID: OpRecoverDestination,
		Method:      "POST",
		Path:        "/v1/namespaces/{namespace}/certificates/{name}/actions/recover-destination",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "namespaces"}, {Param: "namespace"}, {Literal: "certificates"}, {Param: "name"}, {Literal: "actions"}, {Literal: "recover-destination"}},
		Statuses:    []string{"202", "400", "401", "403", "404", "406", "409", "410", "429", "5XX"},
	},
	{
		OperationID: OpGetExposure,
		Method:      "GET",
		Path:        "/v1/exposure",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "exposure"}},
		Statuses:    []string{"200", "400", "401", "403", "406", "429", "503", "5XX"},
	},
	{
		OperationID: OpAdoptOwnership,
		Method:      "POST",
		Path:        "/v1/admin/destinations/{destinationHash}/actions/adopt-ownership",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "admin"}, {Literal: "destinations"}, {Param: "destinationHash"}, {Literal: "actions"}, {Literal: "adopt-ownership"}},
		Statuses:    []string{"200", "400", "401", "403", "404", "406", "409", "429", "5XX"},
	},
	{
		OperationID: OpListRetained,
		Method:      "GET",
		Path:        "/v1/admin/retained",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "admin"}, {Literal: "retained"}},
		Statuses:    []string{"200", "401", "403", "406", "429", "5XX"},
	},
	{
		OperationID: OpForceReconcile,
		Method:      "POST",
		Path:        "/v1/admin/reconcile",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "admin"}, {Literal: "reconcile"}},
		Statuses:    []string{"202", "401", "403", "406", "409", "429", "5XX"},
	},
	{
		OperationID: OpRunMigration,
		Method:      "POST",
		Path:        "/v1/admin/migrations/{migrationNumber}/run",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "admin"}, {Literal: "migrations"}, {Param: "migrationNumber"}, {Literal: "run"}},
		Statuses:    []string{"202", "401", "403", "404", "406", "409", "429", "5XX"},
	},
	{
		OperationID: OpRebuildDueIndex,
		Method:      "POST",
		Path:        "/v1/admin/rebuild-due-index",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "admin"}, {Literal: "rebuild-due-index"}},
		Statuses:    []string{"202", "401", "403", "406", "409", "429", "5XX"},
	},
	{
		OperationID: OpAcceptRestore,
		Method:      "POST",
		Path:        "/v1/admin/accept-restore",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "admin"}, {Literal: "accept-restore"}},
		Statuses:    []string{"200", "400", "401", "403", "406", "409", "429", "5XX"},
	},
	{
		OperationID: OpPurgeForeignChallengeValue,
		Method:      "POST",
		Path:        "/v1/admin/dns/actions/purge-foreign-challenge-value",
		Segments:    []RouteSegment{{Literal: "v1"}, {Literal: "admin"}, {Literal: "dns"}, {Literal: "actions"}, {Literal: "purge-foreign-challenge-value"}},
		Statuses:    []string{"200", "400", "401", "403", "404", "406", "409", "429", "5XX"},
	},
}

// splitPath normalises a dialled path into segments. A trailing slash is not a different
// address, and neither is the leading one.
func splitPath(path string) []string {
	trimmed := strings.TrimPrefix(strings.TrimSuffix(path, "/"), "/")
	if trimmed == "" {
		return nil
	}
	return strings.Split(trimmed, "/")
}

func (r Route) match(segments []string) (map[string]string, bool) {
	if len(r.Segments) != len(segments) {
		return nil, false
	}
	var params map[string]string
	for i, segment := range r.Segments {
		if segment.Param == "" {
			if segment.Literal != segments[i] {
				return nil, false
			}
			continue
		}
		if segments[i] == "" {
			return nil, false
		}
		if params == nil {
			params = map[string]string{}
		}
		params[segment.Param] = segments[i]
	}
	return params, true
}

func (r Route) literals() int {
	n := 0
	for _, segment := range r.Segments {
		if segment.Param == "" {
			n++
		}
	}
	return n
}

// RoutesForPath returns every route the path resolves to, whatever the method, together with the
// captured path parameters. A literal segment beats a template one, so an operation at a fixed
// address is never shadowed by a parameterised sibling of the same length.
//
// The method-blind form is what lets the fake answer 405 for a documented address dialled with
// the wrong verb, rather than the 404 a test author would read as "the contract has no such
// endpoint".
func RoutesForPath(path string) ([]Route, map[string]string, bool) {
	segments := splitPath(path)
	var matched []Route
	var params map[string]string
	best := -1
	for _, route := range Routes {
		captured, ok := route.match(segments)
		if !ok {
			continue
		}
		literals := route.literals()
		if literals < best {
			continue
		}
		if literals > best {
			matched, params, best = nil, captured, literals
		}
		matched = append(matched, route)
	}
	return matched, params, len(matched) > 0
}

// MatchRoute resolves a dialled method and path onto exactly one contract operation.
func MatchRoute(method, path string) (Route, map[string]string, bool) {
	candidates, params, ok := RoutesForPath(path)
	if !ok {
		return Route{}, nil, false
	}
	for _, route := range candidates {
		if route.Method == method {
			return route, params, true
		}
	}
	return Route{}, nil, false
}

// DeclaresStatus reports whether the contract declares this status for this operation. Wildcard
// ranges are honoured: `5XX` covers 500 through 599.
func (r Route) DeclaresStatus(status int) bool {
	exact := strconv.Itoa(status)
	if len(exact) != 3 {
		return false
	}
	for _, declared := range r.Statuses {
		if declared == exact {
			return true
		}
		if len(declared) == 3 && declared[0] == exact[0] &&
			strings.EqualFold(declared[1:], "XX") {
			return true
		}
	}
	return false
}
